=head1 NAME

bbbike - Informationssystem fE<uuml>r Radfahrer in Berlin und Brandenburg

=head1 SYNOPSIS

  bbbike [options]

=head1 BESCHREIBUNG

B<BBBike> ist ein Informationssystem fE<uuml>r Radfahrer in Berlin und
Brandenburg. Mit dem Programm kE<ouml>nnen Routen, optimiert fE<uuml>r
Radfahrer, automatisch gesucht oder manuell erstellt werden. Bei der
automatischen Suche wird die kE<uuml>rzeste Strecke zwischen zwei
angegebenen Punkten gesucht. Bei der manuellen Routenerstellung
kE<ouml>nnen abschnittsweise Zwischenpunkte eingegeben werden und zum
Schluss die GesamtlE<auml>nge abgelesen werden.

Eine einfache WWW-Version kann man unter der Adresse
L<http://www.bbbike.de> finden.

Wenn eine Verbindung zum Internet existiert, kann B<BBBike> die
aktuellen Wetterdaten von der FU Berlin (Dahlem) die WindstE<auml>rke
und -richtung auswerten. Diese Daten können bei der Berechnung der
Fahrzeit und Leistung verwendet werden.

Ein Teil von B<BBBike> ist das perl-Modul L<BikePower|BikePower>. Mit
diesem Modul kann (wie beim ursprE<uuml>nglichen
B<bike_power>-Programm von Ken Roberts - roberts@cs.columbia.edu )
anhand von Daten wie GefE<auml>lle, Wind, Rollwiderstand der Reifen,
Luftwiderstand, Masse von Rad und Fahrer die Leistung ermittelt
werden.

B<BBBike> liefert unter anderem die Antwort auf folgende Fragen:

=over 4

=item *

Wie lang ist die Strecke von A nach B?

=item *

Wie lange brauche ich von A nach B, wenn ich durchschnittlich 15 km/h 
schnell fahre?

=item *

Wie lange brauche ich von A nach B, wenn ich mit 100 Watt Leistung
fahre, mit BerE<uuml>cksichtigung des aktuellen Windes und von Steigungen
auf der Strecke?

=item *

Auf welchen StraE<szlig>en muss ich fahren und wie muss ich abbiegen,
wenn ich von A nach B kommen will?

=item *

Wo habe ich Gegenwind- und RE<uuml>ckenwindstrecken?

=item *

Wo gibt es Steigungen und GefE<auml>lle?

=item *

Kann ich HauptstraE<szlig>en und/oder Kopfsteinpflasterstrecken auf
meiner Strecke vermeiden?

=item *

Kann ich E<quot>grE<uuml>neE<quot> Wege auf meiner Strecke bevorzugen?
Kann ich unbeleuchtete StraE<szlig>en meiden?

=back

=head2 AUTOMATISCHE SUCHE

Start- und Zielpunkt einer Route setzt man, indem man mit der linken
Maustaste auf eine StraE<szlig>e klickt. Nach dem Setzen des
Zielpunktes berechnet das Programm die kE<uuml>rzeste Route und zeigt
sie an. Danach kann die Route mit Klick verlE<auml>ngert werden. Soll
eine neue Route (mit neuem Start- und Zielpunkt) berechnet werden,
kann die alte mit dem KontextmenE<uuml>punkt E<quot>Route
lE<ouml>schenE<quot> oder mit Klick auf das Icon B<Route
löschen> gelE<ouml>scht werden. Mit der Backspace-Taste
kann der letzte Punkt der Route gelE<ouml>scht werden. Mit der
Delete-Taste (Entf) kann die Route bis zum letzten Via-Punkt
gelE<ouml>scht werden.

Die Route kann eingefE<auml>rbt werden (MenE<uuml>punkt Route >
EinfE<auml>rben der Route), und zwar rot, schwarz, blau oder nach
Windrichtung oder Leistung. FE<uuml>r das EinfE<auml>rben nach
Windrichtung benE<ouml>tigt man Winddaten (automatisch aus dem WWW
geholt oder manuell eingegeben). Die RE<uuml>ckenwindstrecken werden
dann grE<uuml>n und die Gegenwindstrecken rot dargestellt. FE<uuml>r
das EinfE<auml>rben nach Leistung benE<ouml>tigt man zusE<auml>tzlich
die persE<ouml>nlichen Daten des Fahrers (siehe
L<Bikepower|"Fahrrad-Symbol">).

=head2 MANUELLE ROUTENERSTELLUNG

Die manuelle Routenerstellung wird zum Beispiel bei der Erstellung
einer Tourplanung verwendet, bei der nicht das Suchen einer
kE<uuml>rzesten Strecke im Vordergrund steht. Sie funktioniert
prinzipiell wie die B<automatische Suche>, nur wird der Benutzer
mehrere Zwischenpunkte eingeben, um die Route festzulegen. Mit Klick
auf Alt-Button1 oder Shift-Button1 (Klick auf die linke Maustaste und
gleichzeitiges DrE<uuml>cken der Alt- oder Shift-Taste) kann ein
beliebiger Punkt gekennzeichnet werden (also ein Punkt, der nicht auf
einer StraE<szlig>e liegt).

=head1 INFORMATIONSLEISTE

Im oberen Bereich des Fensters, unterhalb der Menüleiste (falls
eingeblendet), befindet sich die Informationsleiste von BBBike.

=over 4

=item Ort/Bahnhof

Anzeige des Ortes bzw. der Haltestelle unter dem Mauscursor. Die
Angabe ist nur gE<uuml>ltig, wenn sie in schwarzer Schrift (und nicht
in grauer) erscheint. Mit einem Klick wird die Ort-Auswahl angezeigt.

=item StraE<szlig>e/Strecke

Anzeige der StraE<szlig>e bzw. Bahnlinie unter dem Mauscursor. Auch
hier ist die Angabe nur bei schwarzer Schrift gE<uuml>ltig. Mit einem
Klick wird die StraE<szlig>en-Auswahl angezeigt.

=item km

LE<auml>nge der aktuellen Route in Kilometern. Mit Klick auf den
Schriftzug E<quot>kmE<quot> kann zwischen der Angabe in Kilometern und
Metern umgeschaltet werden. Falls englisch als Sprache eingestellt
wurde, ist auch die Auswahl "Meilen" möglich.

=item %

Angabe, wieviel % E<uuml>ber der Ideallinie (Luftlinie) die aktuelle
Route liegt. Bei offensichtlichen Rundfahrten bleibt die Angabe leer.

=item km/h

Fahrzeit bei dieser durchschnittlichen Geschwindigkeit. Mit Klick auf
das km/h-Feld kann eine andere Geschwindigkeit eingegeben werden. Mit
Klick auf die Fahrzeit wird das Alarm-Fenster geE<ouml>ffnet. Mit der
rechten Maustaste kann die jeweilige Geschwindigkeit als
E<quot>ReferenzgeschwindigkeitE<quot> ausgewE<auml>hlt werden. Mit dem
Ampel-Icon kann das Einbeziehen von Ampeln in die Fahrzeit
ein-/ausgeschaltet werden. Mit dem Kopfsteinpflaster-Icon unterhalb
des Ampel-Icons kann das Einbeziehen von Kopfsteinpflaster- und
E<auml>hnlichen Strecken in die Fahrzeit ein-/ausgeschaltet werden.

=item W

Fahrzeit bei dieser durchschnittlichen Leistung, abhE<auml>ngig von
der Windgeschwindigkeit und von Steigungen. Die Berechnung wird mit
dem Modul L<BikePower|BikePower> durchgefE<uuml>hrt. Mit Klick auf das
W-Feld kann eine andere Leistung (in Watt) eingegeben werden. Als
Faustregel kann man 50W für eine gemütliche Fahrweise annehmen. Mit
Klick auf die Fahrzeit wird das Alarm-Fenster geE<ouml>ffnet. Mit der
rechten Maustaste kann die jeweilige Leistung als
E<quot>ReferenzleistungE<quot> (intern wird diese auf eine
Geschwindigkeit umberechnet) ausgewE<auml>hlt werden. Auch hier kann
man mit Ampel- und Kopfsteinpflaster-Icon zum Einbeziehen von
Ampeln/Kopfsteinpflasterstrecken in die Fahrzeit einbeziehen.

=item Datum der Winddaten

Falls aktuelle Winddaten vorhanden sind, stehen in diesem Feld das
jeweilige Datum und die Uhrzeit. Bei einem Mausklick wird versucht,
die aktuellen Daten E<uuml>ber das WWW oder E<uuml>ber eine lokale
Datenbank zu holen. Mit der rechten Maustaste erscheint ein MenE<uuml>
mit folgenden Punkten:

=over 4

=item Wetterstation

Hier kann ausgewE<auml>hlt werden, welche der Quellen im Internet
(Meteorologisches Institut der FU oder ggfs. andere Quellen)
verwendet werden soll. Mit "aktuellste" werden alle Quellen nach den
aktuellsten Angaben E<uuml>berprE<uuml>ft.

=item Quelle

Hier kann angegeben werden, ob die Wetterdaten E<uuml>ber das Internet
direkt gezogen werden oder ob ein evtl. vorhandener lokaler Cache bzw
eine lokale Datenbank vorgezogen wird.

=item Auswahl aus Datenbank

Falls eine lokale Datenbank vorhanden ist, kE<ouml>nnen hiermit
Wetterdaten zu einem bestimmten Tag ausgewE<auml>hlt werden.

=item Wind ignorieren

Normalerweise wird - falls Winddaten vorhanden sind - die Route anhand
der Windrichtung gefE<auml>rbt: RE<uuml>ckenwindabschnitte sind
grE<uuml>n, Gegenwindabschnitte rot und Seitenwindabschnitte von
hellgrE<uuml>n bis orange.

Falls der MenE<uuml>punkt "Wind ignorieren" angeklickt ist, wird die
Windgeschwindigkeit und -richtung bei der Route und bei der
Zeitberechnung ignoriert. Die Route wird dann in einer einzelnen Farbe
(blau) gezeichnet.

=item Aktualisierung

Hiermit kann das Zeichnen der Gegenwind- und RE<uuml>ckenwindstrecken
der Route aktualisiert werden.

=item automatische Aktualisierung

Beim E<Auml>ndern der Wetterstation bzw. der Quelle werden automatisch
die neuen Wetterdaten geholt.

=item automatische Routenaktualisierung

Beim E<Auml>ndern von Wetterdaten werden automatisch die Gegenwind-
und RE<uuml>ckenwindstrecken der Route aktualisiert.

=back

=item Winddaten

Hier wird, falls vorhanden, die aktuelle Windrichtung und die aktuelle
Windgeschwindigkeit in m/s angezeigt. Mit einem Klick wird ein Fenster
zur manuellen Eingabe der Windrichtung und -geschwindigkeit
geE<ouml>ffnet. I<Anmerkung>: Zwar kann die maximale Windgeschwindigkeit
eingegeben werden, das Programm verwendet aber nur die mittlere
Windgeschwindigkeit fE<uuml>r die Zeitberechnungen.

=item Temp

Anzeige der aktuellen Temperatur. Die Temperatur wird sogar in die
Leistungsberechnung einbezogen, die Auswirkungen darauf sind aber nur
minimal.

=back

=head1 ICONS

Unter manchen Icons befindet sich ein kleiner Pfeil, mit dem ein
zugehE<ouml>riges Popup-MenE<uuml> aufgeklappt werden kann. Das
MenE<uuml> kann auch mit Klick auf die rechte Maus-Taste,
wE<auml>hrend sich der Maus-Cursor E<uuml>ber dem Icon befindet,
aufgerufen werden.

Hier folgt die Beschreibung der Icons von links nach rechts.

=head2 KARTENELEMENTE

Die erste Gruppe kontrolliert, welche Elemente auf der
KartenflE<auml>che dargestellt werden sollen. In allen MenE<uuml>s
dieser Icons kann mit B<oben>, B<normal> und B<unten> angegeben
werden, ob die Elemente E<uuml>ber oder unter allen anderen Elementen
gezeichnet werden sollen oder ob die normale Reihenfolge
wiederhergestellt werden soll (die normale Reihenfolge lautet von
unten nach oben: FlE<auml>chen, GewE<auml>sser, Inseln, Grenzen,
U-Bahnen, Regionalbahnen, S-Bahnen, StraE<szlig>en,
LandstraE<szlig>en, Orte). Daneben besitzt jedes MenE<uuml> einen
Schalter zum Ein- und Ausschalten des Elements und einen Eintrag zum
AuswE<auml>hlen einer bestimmten StraE<szlig>e oder eines bestimmten
Ortes E<uuml>ber eine Listbox.

=over 4

=item StraE<szlig>en-Symbol

=for html <img src="images/strasse.gif" alt="icon strasse">

Schaltet das Zeichnen von StraE<szlig>en in Berlin ein oder aus
(Tastatur: C<s>).

MenE<uuml>: Neben den StandardeintrE<auml>gen sind noch folgende
EintrE<auml>ge vorhanden:

=over 4

=item Auswahl aus ...

In diesem UntermenE<uuml> kann eine StraE<szlig>e aus alternativen
Verzeichnissen ausgewE<auml>hlt werden:

=over 4

=item Komplette StraE<szlig>enliste

In der StraE<szlig>en-Datenbank von B<BBBike> sind nur ca. 2300
StraE<szlig>en erfasst. StraE<szlig>en, die hier nicht vorhanden sind,
kE<ouml>nnen in der umfangreicheren PLZ-Datenbank ausgewE<auml>hlt
werden. Allerdings wird bei der Auswahl einer nicht vorhandenen
StraE<szlig>e nur der Postleitzahlbereich angezeigt.

=item Telefonbuch-Datenbank (StraE<szlig>e)

Wenn eine Telefonbuch-CD-ROM 1998/99 oder 1999/2000 fE<uuml>r Berlin
vorhanden ist, kann diese Datenbank verwendet werden. Hier kann jede
StraE<szlig>e mit Hausnummer angegeben werden; die Position wird recht
exakt angzeigt.

=item Telefonbuch-Datenbank (Name)

Mit diesem Formular kann nach Namen im Telefonbuch-Verzeichnis gesucht
werden. Es muss mindestens der Nachname angegeben werden. Mit dem
Schalter B<Exakt> kann eingestellt werden, ob der Nachname exakt
passen muss (ansonsten wird bei der Suche von "Wall" auch "Wallburg"
etc. angezeigt). Nachdem mit B<Suchen> die Ergebnisliste erstellt
wurde, kE<ouml>nnen mit B<E<lt>E<lt>> und B<E<gt>E<gt>> weitere
passende DatensE<auml>tze eingesehen werden. Mit B<Alle> werden alle
passenden DatensE<auml>tze auf der Karte markiert. Wenn ein
C<dial>-Programm vorhanden ist, erscheint noch ein Button
B<WE<auml>hlen> zum WE<auml>hlen der Telefonnummer.

=back

=item UntermenE<uuml> StraE<szlig>enkategorien

In diesem UntermenE<uuml> kann das Zeichnen von HauptstraE<szlig>en,
NebenstraE<szlig>en und fE<uuml>r Kfz gesperrte StraE<szlig>en ein-
und ausgeschaltet werden.

=item HE<ouml>henpunkte

HE<ouml>henpunkte werden in die Karte eingezeichnet.

=item Radwege

Radwege werden gezeichnet. Benutzungspflichtige Radwege sind
dunkelblau, freiwillig zu nutzende Radwege blau, Radstreifen
grE<uuml>n und Busspuren orange. FE<uuml>r jede Richtung, in die ein
Radweg existiert, wird auf der jeweiligen StraE<szlig>enseite ein
Radweg gezeichnet, auch wenn es sich eigentlich um einen
Zwei-Richtungs-Radweg auf der falschen StraE<szlig>enseite handelt.

=item UntermenE<uuml> Radwegekategorien

In diesem UntermenE<uuml> kann das Zeichnen von einigen
Radwegekategorien ein- und ausgeschaltet werden.

=item Einbahn-/gesperrte StraE<szlig>en

Kennzeichnung von EinbahnstraE<szlig>en (blaue Pfeile, die in die
StraE<szlig>enrichtung zeigen), gesperrten StraE<szlig>en (rote
Kreuze) sowie Punkten, an denen das Fahrrad getragen werden muss (drei
waagerechte Striche). TemporE<auml>re Sperrungen wegen Bauarbeiten
werden mit einem Baustellen-Symbol gekennzeichnet.

=item FE<auml>hren

Zeichnen von FE<auml>hren. Um die FE<auml>hren auch in der Suche mit
einzubeziehen, muss im MenE<uuml> von B<Route suchen> der Eintrag
B<FE<auml>hren verwenden> aktiviert sein.

=item Ampeln

Ampeln werden in die Karte eingezeichnet. Bei der Auswahl einer Route
wird die Anzahl der durchgefahrenen Ampeln mit einer ungefE<auml>hren
VerzE<ouml>gerungszeit (15 Sekunden pro Ampel) im Feld rechts von den
Icons angezeigt.

Reine FuE<szlig>gE<auml>ngerampeln sind in der Datenbasis nur erfasst,
wenn sie die Fahrt wesentlich verzE<ouml>gern wE<uuml>rden (hohe
FuE<szlig>gE<auml>ngerfrequenz oder stark befahrene QuerstraE<szlig>e
direkt vor oder hinter der Ampeln). Beschrankte
BahnE<uuml>bergE<auml>nge sind ebenfalls unter den Ampeln zu finden.

=item Outline zeichnen

Die StraE<szlig>en werden mit Umrandung gezeichnet.

=item StraE<szlig>ennamen

Die StraE<szlig>en werden mit StraE<szlig>ennamen gezeichnet. Ist
wesentlich langsamer, besonders wenn B<Font rotation> eingeschaltet
ist.

=item StraE<szlig>enqualitE<auml>t

Die QualitE<auml>t des StraE<szlig>enbelags wird gezeichnet. Die
Kategorisierung siegt wie folgt aus:

=over 8

=item dunkelgrE<uuml>n

Sehr guter Belag (meist Asphalt). Da die meisten StraE<szlig>en einen
guten Belag haben, wurde auf eine Erfassung dieser Kategorie meist
verzichtet.

=item hellgrE<uuml>n

Guter Belag, z.B. gutes Kopfsteinpflaster oder etwas schlechterer
Asphalt.

=item orange

ME<auml>E<szlig>iger Belag, z.B. die meisten
KopfsteinpflasterstraE<szlig>en.

=item rot

Schlechter Belag (schlechtes Kopfsteinpflaster, unbefestigte Wege).

=back

=item QualitE<auml>tskategorien

Hiermit kann das Zeichnen der QualitE<auml>tskategorien
eingeschrE<auml>nkt werden.

=item Sonstige Behinderungen

Zeichnen von sonstigen Behinderungen (z.B.
FuE<szlig>gE<auml>ngerverkehr).

=back

=item LandstraE<szlig>en-Symbol

=for html <img src="images/landstrasse.gif" alt="icon landstrasse">

Schaltet das Zeichnen von LandstraE<szlig>en in Berlins Umgebung ein
oder aus (Tastatur: C<l>).

MenE<uuml>: Neben den StandardeintrE<auml>gen sind noch folgende
EintrE<auml>ge vorhanden:

=over 4

=item Outline zeichnen

Gleiche Funktion wie beim StraE<szlig>en-Symbol.

=item LandstraE<szlig>en jwd zeichnen

Zeichnet auch LandstraE<szlig>en auE<szlig>erhalb Brandenburgs.

=item StraE<szlig>enqualitE<auml>t

Gleiche Funktion wie beim StraE<szlig>en-Symbol.

=item Sonstige Behinderungen

Gleiche Funktion wie beim StraE<szlig>en-Symbol.

=back

=item Ort-Symbol

=for html <img src="images/ort.gif" alt="icon ort">

Schaltet das Zeichnen von Orten in Brandenburg ein oder aus (Tastatur:
C<o>).

MenE<uuml>: Neben den StandardeintrE<auml>gen sind noch folgende
EintrE<auml>ge vorhanden:

=over 4

=item Ortsnamen

Anzeige von B<Ortsnamen> ermE<ouml>glichen oder unterbinden.

=item Kategorie

In diesem UntermenE<uuml> kann das Zeichnen von kleineren Orten
unterdrE<uuml>ckt werden. Beispielorte fE<uuml>r die Kategorisierung:

	6	Berlin
	5	Potsdam, Brandenburg
	4	Werder, Kyritz
	3	Ketzin, Lindow
	2	Caputh, Göttin
	1	Krummensee
	0	Ortsteile wie Wilhelmsdorf, Döthen,
		Petzow

Mit E<quot>AlleE<quot> werden alle Orte gezeichnet. Mit
E<quot>AutoE<quot> werden die Orte abhE<auml>ngig von der Zoom-Stufe
gezeichnet.

=item SchriftgrE<ouml>E<szlig>e

UntermenE<uuml> zum Einstellen einer anderen SchriftgrE<ouml>E<szlig>e
fE<uuml>r die Anzeige der Ortsnamen. Der Bereich geht von "klein" bis
"sehr groE<szlig>".

=item E<Uuml>berlappungen vermeiden

Hier wird mit einem sehr einfachen Algorithmus versucht, die
Ortsbeschriftungen so zu setzen, dass sie sich nicht einander
E<uuml>berlappen. Per Voreinstellung ist diese Option ausgeschaltet,
weil das Zeichnen der Orte dadurch erheblich verlangsamt wird.
Sinnvoll ist diese Option, wenn z.B. die Karte als Bilddatei
abgespeichert werden soll.

=back

=item U-Bahn-Symbol

=for html <img src="images/ubahn.gif" alt="icon ubahn">

Schaltet das Zeichnen von U-Bahnlinien ein oder aus (Tastatur: C<u>).

MenE<uuml>: ZusE<auml>tzlich zum Ein-/Ausschalten und AuswE<auml>hlen
der U-Bahnlinien kE<ouml>nnen auch U-BahnhE<ouml>fe ein-/ausgeschaltet
und ausgewE<auml>hlt werden.

Wenn der Punkt B<U-Bhf-Namen> angeklickt wird, werden die jeweiligen
Namen zum U-Bahnhof auf der Karte eingezeichnet. Mit
B<E<Uuml>berlappungen vermeiden> wird versucht, die Namen so zu
setzen, dass sie sich nicht einander E<uuml>berlappen. Siehe auch die
Bemerkung zu B<E<Uuml>berlappungen vermeiden> im MenE<uuml>punkt
B<Ort-Symbol>.

Mit B<VBB-Zone A>, B<VBB-Zone B> und B<in Bau> kann das U-Bahn-Netz
zusE<auml>tzlich auf die jeweilige Zone eingeschrE<auml>nkt werden.

=item S-Bahn-Symbol

=for html <img src="images/sbahn.gif" alt="icon sbahn">

Schaltet das Zeichnen von S-Bahnlinien ein oder aus (Tastatur: C<b>).

MenE<uuml>: Wie beim U-Bahn-Symbol.

=item RB-Symbol

=for html <img src="images/rbahn.gif" alt="icon rbahn">

Schaltet das Zeichnen von Regionalbahnlinien ein oder aus (Tastatur: C<r>).

MenE<uuml>: Wie beim U-Bahn-Symbol.

=item GewE<auml>sser-Symbol

=for html <img src="images/wasser.gif" alt="icon wasser">

Schaltet das Zeichnen von FlE<uuml>ssen, KanE<auml>len und Seen ein
oder aus (Tastatur: C<w>).

MenE<uuml>: Neben den StandardeintrE<auml>gen sind noch folgende
EintrE<auml>ge vorhanden:

=over 4

=item Outline zeichnen

Wie beim gleichnamigen Eintrag beim StraE<szlig>en-Symbol.

=item Namen der GewE<auml>sser

Schaltet das Zeichnen der GewE<auml>ssernamen ein oder aus.

=item GewE<auml>sser im Umland zeichnen

Schaltet das Zeichnen der GewE<auml>sser im Umland von Berlin ein oder aus.

=item GewE<auml>sser in der Stadt zeichnen

Schaltet das Zeichnen der GewE<auml>sser in Berlin ein oder aus.

=back

=item FlE<auml>chen-Symbol

=for html <img src="images/flaechen.gif" alt="icon flaechen">

Schaltet das Zeichnen von sonstigen FlE<auml>chen (Parks,
WE<auml>lder, FlughE<auml>fen) ein oder aus (Tastatur: C<f>).

MenE<uuml>: Neben den StandardeintrE<auml>gen sind noch folgende
EintrE<auml>ge vorhanden:

=over 4

=item PLZ-Gebiete

Schaltet das Zeichnen der Berliner Postleitzahlgrenzen ein oder aus.
Die PLZ-Datenbank ist noch im Aufbau.

=item PLZ-Gebiet auswE<auml>hlen

Zeigt eine Listbox zum AuswE<auml>hlen einer Berliner Postleitzahl an.

=item Grenzen von Berlin

Schaltet das Zeichnen der Berliner Stadtgrenze ein oder aus.

=back

=item Sehenswürdigkeiten-Symbol

=for html <img src="images/star.gif" alt="icon stern">

Schaltet das Zeichnen von Sehenswürdigkeiten und anderen wichtigen
Gebäuden ein oder aus. Im MenE<uuml> gibt es die weiteren Punkte:

=over 4

=item SehenswE<uuml>rdigkeiten

Schaltet das Zeichnen von SehenswE<uuml>rdigkeiten und anderen
markanten GebE<auml>uden in Berlin und Brandenburg ein oder aus.

=item SehenswE<uuml>rdigkeit auswE<auml>hlen

Zeigt eine Listbox zum AuswE<auml>hlen einer SehenswE<uuml>rdigkeit
an.

=item Kneipen

Zeichnet genau wie die SchaltflE<auml>che Kneipen in Berlin.

=item Kneipe auswE<auml>hlen

Zeigt eine Listbox zum AuswE<auml>hlen einer Kneipe an.

=item PersE<ouml>nliche Orte

Zeigt eine Listbox mit persE<ouml>nlich eingetragenen Orten ein. Die
Punkte mE<uuml>ssen im C<bbd>-Format in der Datei
C<$HOME/.bbbike/personal.bbd> vorhanden sein.

=item Obst

Zeichnet Stellen mit E<ouml>ffentlich zugE<auml>nglichen
ObstbE<auml>umen.

=back

=item Zusätzliche Kartenebenen-Symbol

=for html <img src="images/newlayer.gif" alt="icon neuer layer">

Im MenE<uuml> gibt es die Punkte:

=over 4

=item Straßen-Layer zeichnen

Zeichnet bbd- und andere GPS/GIS-Dateien als
Straßen/Strecken/Flächen.

=item Sperrungen-Layer zeichnen

Zeichnet bbd-Dateien als E<quot>SperrungenE<quot> (gesperrte Straßen,
Einbahnstraßen etc.). Das Straßennetz wird entsprechend der Sperrungen
aktualisiert.

=item Punkte-Layer zeichnen

Zeichnet bbd- und andere GPS/GIS-Dateien als Punkte.

=item Straßen/Punkte auswählen

Auswahl eines Objekts aus einer neu gezeichneten Kartenebene anhand
des Namens.

=item Letzte geöffnete Layer

Zeigt ein Menü der zuletzt geöffneten Kartenebenen/Layer.

=item Umordnen

Zeigt einen Dialog, in dem die Kartenebenen umgeordnet werden können.
Zurzeit nur unter Unix/X11 möglich.

=item Layer löschen

Löschen einer zusätzlich gezeichneten Kartenebene.

=item Ausschnitt an Layer anpassen

Der sichtbare Ausschnitt wird so geändert, dass die gesamte neue
Kartenebene sichtbar ist.

=item Scrollregion an Layer anpassen

Der Scrollbereich wird auf die Bounding Box der neuen Kartenebene
gesetzt.

=item Scrollregion für Layer vergrößern.

Der Scrollbereich wird, falls notwendig, so vergrößert, dass die neue
Kartenebene vollständig enthalten ist. Dieser Menüpunkt ist bevorzugt
von den Scrollregion/Ausschnitt-Menüpunkten zu verwenden.

=item Linienbreite 1 Punkt

Die Linienbreite bei neuen Strecken wird auf einen Punkt gesetzt.

=item WWW-Klickmodus

Falls in den Namen der neuen Kartenobjekte URLs enthalten sind, können
diese beim Klicken im Web-Browser geladen werden.

=item Gpsman-Daten zeichnen

Spezielles Zeichnen von Daten, die im gpsman-Format vorliegen.

=item GPS-Track-Animation

Animation von zuvor mit dem im Menüpunkt E<quot>Gpsman-Daten
zeichnenE<quot> Tracks.

=back

=back

=head2 NAVIGATION

In der nE<auml>chsten Gruppe sind die Navigations-Icons:

=over 4

=item VergrE<ouml>E<szlig>ern-Symbol (+)

Es wird ein kleinerer Ausschnitt angezeigt (mehr Details). Tastatur:
C<+>. 

=item Verkleinern-Symbol (-)

Es wird ein grE<ouml>E<szlig>erer Ausschnitt angezeigt (weniger
Details). Tastatur: C<->.

=item MaE<szlig>stab-Feld

Dieses Feld zeigt den aktuellen MaE<szlig>stab, bezogen auf den
Bildschirm, an. Die Zahl stimmt nur, wenn die DPI-Zahl des X-Servers
korrekt eingetragen wurde (beim X-Server von XFree86 kann die DPI-Zahl
mit der Option I<-dpi> verE<auml>ndert werden). Mit Klick auf das Feld
kann ein anderer MaE<szlig>stab angegeben werden und so der
Kartenausschnit vergrE<ouml>E<szlig>ert oder verkleinert werden.

=item E<Uuml>bersichtskarten-Symbol

=for html <img src="images/berlin_overview_small.gif" alt="icon uebersichtskarte berlin">

Mit diesem Symbol kann die E<Uuml>bersichtskarte von Berlin und
Brandenburg ein- und ausgeschaltet werden. In der
E<Uuml>bersichtskarte wird der aktuelle Ausschnitt durch ein schwarzes
Rechteck gekennzeichnet. Durch Verschieben dieses Rechtecks wird auch
der aktuelle Ausschnitt verschoben.

=item Windrosen-Symbol

=for html <img src="images/windrose.gif" alt="icon windrose">

Mit dem Windrosen-Symbol kann man die Karte in die vier
Himmelsrichtungen scrollen. Mit der linken Maustaste sind dabei die
Schritte kleiner, mit der mittleren grE<ouml>E<szlig>er. Wenn man
lE<auml>nger auf die Mitte der Windrose klickt (ca. 2 Sekunden), wird
wieder zurE<uuml>ck auf die Mitte zentriert. Scrollen kann man auch
mit den Scrollbars oder mit den Tasten I<Pos1> (links), I<Ende>
(rechts), I<Bild nach oben> und I<Bild nach unten> (jeweils immer
seitenweise) bzw. mit den Cursortasten (feinere Abstufung).

=back

=head2 ROUTEN

Die folgenden Icons kontrollieren die Suche von Routen:

=over 4

=item Route suchen

=for html <img src="images/search.gif" alt="icon suche">

Mit diesem Schalter kann man den Suchmodus ein- oder ausschalten.
Normalerweise ist dieser Schalter nicht aktiviert und es ist immer der
Suchmodus eingeschaltet (kann mit der Kommandozeilen-Option
I<-advanced> geE<auml>ndert werden).

MenE<uuml>:

=over 4

=item Route lE<ouml>schen

Die aktuelle Route wird gelE<ouml>scht. Gleiche Funktion wie
DrE<uuml>cken auf C<Shift-Backspace>.

Der letzte Punkt der Route wird mit der Backspace-Taste gelE<ouml>scht.

=item Route wiederherstellen (Undo)

Die zuletzt gelE<ouml>schte Route wird wiederhergestellt.

=item Route aktualisieren

Die Route wird in Bezug auf Wind und Leistung aktualisiert (sollte nicht
notwendig sein).

=item gesperrte StraE<szlig>en beachten

Wenn dieser Schalter eingeschaltet ist, werden gesperrte
StraE<szlig>en und EinbahnstraE<szlig>en nicht in die Suche
einbezogen.

=item Tragen vermeiden

Stellen, an denen das Rad getragen werden muss, werden nicht in die
Suche einbezogen.

=item FE<auml>hren verwenden

FE<auml>hren werden bei der Suche berE<uuml>cksichtigt.

=item Steigungen berechnen

HE<ouml>henangaben werden eingelesen und bei der Berechnung der
Leistung werden die HE<ouml>henangaben fE<uuml>r Steigungen und
GefE<auml>lle verwendet.

=item Ampel-Optimierung

Bei der Suche einer Route wird fE<uuml>r jede Ampel 25m, 50m oder 100m
auf die entsprechende Strecke aufgeschlagen (nur fE<uuml>r den
Suchalgorithmus). AbhE<auml>ngig von der Geschwindigkeit bekommt man
fE<uuml>r die VerzE<ouml>gerungszeit pro Ampel folgende Tabelle:

=for text
		15km/h	20km/h	25km/h
	25m	6s	5s	4s
	50m	12s	9s	7s
	100m	24s	18s	14s

=for html
<table border=1>
<th><th>15km/h	<th>20km/h	<th>25km/h
<tr><td>25m	<td>6s		<td>5s		<td>4s
<tr><td>50m	<td>12s		<td>9s		<td>7s
<tr><td>100m	<td>24s		<td>18s		<td>14s
</table>

Zu lesen ist die Tabelle wie folgt: wenn man mit 25km/h unterwegs ist
und als Aufschlag 100m gewE<auml>hlt hat, wE<uuml>rde dies einer
VerzE<ouml>gerung von durchschnittlich 14s pro Ampel entsprechen.

=item Steigungen/GefE<auml>lle zeigen

Auf der Route liegende GefE<auml>lle oder Steigungen E<uuml>ber 1%
werden angezeigt.

=item Startflagge

Schaltet das Zeichnen einer Startflagge am Routenanfangspunkt ein oder
aus.

=item Zielflagge

Schaltet das Zeichnen einer Zielflagge am Routenendpunkt ein oder aus.

=back

=item Sucheinstellungen

=over

=item Einbahn-/gesperrte Straßen beachten

Einbahnstraßen und gesperrte Straßen werden bei der Suche gemieden.

=item Einbahn-/gesperrte Straßen *strikt* beachten

Einige Einbahnstraßen sind als für Radfahrer in der Gegenrichtung
befahrbar gekennzeichnet, obwohl sie es offiziell nicht sind. Mit
dieser Option werden alle Einbahnstraßen gemieden (außer für Radfahrer
offiziell geöffnete).

=item Benutzerdefinierte Sperrungen

In diesem Menü kann man private Sperrungen definieren, laden und
speichern. Wenn der E<quot>DefinierenE<quot>-Modus eingeschaltet wird,
kann mit einem Klick auf eine Straße diese als E<quot>gesperrtE<quot>
gekennzeichnet werden. Ein nochmaliger Klick auf eine Sperrungen hebt
diese auf.

Weiterhin können E<quot>Aktive SperrungenE<quot> geladen werden. Diese
werden ca. wöchenlich (falls man Internet-Updates macht) oder täglich
(falls man Updates per git macht) aktualisiert und enthalten
beispielsweise Baustellen, Brückensperrungen oder Veranstaltungen, die
auch Radfahrer betreffen könnten.

=item Tragen strikt vermeiden

Bei der normalen Suche werden Abschnitte, in denen getragen werden muß
(Treppen) mit einer hohen Penalty versehen. Wenn E<quot>strikt
vermeidenE<quot> gesetzt ist, dann werden solche Strecken komplett
gemieden.

=item Schlechte Wege vermeiden

(Q3 strikt meiden? XXX)

=item Fähren verwenden

Erlaubt die Benutzung von Fähren bei der Suche. Eine Prüfung, ob die
Fähre zum jeweiligen Zeitpunkt überhaupt fährt bzw. ob die Route
dadurch schneller ist, wird nicht gemacht.

=item Straßenqualität-Optimierung

Optimiert nach der Straßenqualität (Asphalt, Kopfsteinpflaster etc.).
Einstellungen werden unter E<quot>Optimierungsparameter
einstellenE<quot> gesetzt.

=item Straßenkategorie-Optimierung

Optimiert nach der Straßenkategorie (Nebenstraße, Hauptstraße etc.).
Einstellungen werden unter E<quot>Optimierungsparameter
einstellenE<quot> gesetzt.

=item Optimierung der sonstigen Behinderungen

Optimiert nach sonstigen Behinderungen (Fußgänger auf der Straße,
Bordsteine, sehr kurvige Strecken etc.). Einstellungen werden unter
E<quot>Optimierungsparameter einstellenE<quot> gesetzt.

=item Ampel-Optimierung

Optimiert nach Anzahl der Ampeln. Einstellungen werden unter
E<quot>Optimierungsparameter einstellenE<quot> gesetzt.

=item Radwege-Optimierung

Optimiert nach Vorhandensein von Radwegen. Einstellungen werden unter
E<quot>Optimierungsparameter einstellenE<quot> gesetzt.

=item Hauptstraßen ohne Radwege/Busspuren meiden

=item Grüne Wege

=item Unbeleuchtete Straßen meiden

=item Steigungsoptimierung

Hierbei werden die BikePower-Daten zur Berechnung verwendet.

=item Abbiege-Optimierung

Noch nicht implementiert.

=item Optimierungsparameter einstellen

=item Penalty

=back

=item Beschreibung der aktuellen Route

=for html <img src="images/strlist.gif" alt="icon strassenliste">

Es wird eine Routenbeschreibung in der folgenden Form angezeigt:

=for text
 LE<auml>nge        Gesamt   Richtung                StraE<szlig>e
 ----------------------------------------------------------------
 nach 0.15 km (0.2 km)                         Franklinstr.
 nach 0.03 km (0.2 km)                         Marchstr.
 nach 0.48 km (0.7 km) rechts (80°) auf den    Ernst-Reuter-Platz
 nach 0.28 km (0.9 km) halbrechts (30°) in die Hardenbergstr.
 nach 0.09 km (1.0 km) angekommen!

=for html
<table border=1>
<th>L&auml;nge<th>Gesamt	<th>Richtung	<th>Stra&szlig;e
<tr><td>nach 0.15 km	<td>(0.2 km) <td> &nbsp;  	          <td>Franklinstr.
<tr><td>nach 0.03 km	<td>(0.2 km) <td> &nbsp;                  <td> Marchstr.
<tr><td>nach 0.48 km	<td>(0.7 km) <td> rechts (80°) auf den    <td> Ernst-Reuter-Platz
<tr><td>nach 0.28 km	<td>(0.9 km) <td> halbrechts (30°) in die <td> Hardenbergstr.
<tr><td>nach 0.09 km	<td>(1.0 km) <td> angekommen!             <td> &nbsp;
</table>
<p>


Diese Beschreibung kann in eine Datei geschrieben, ausgedruckt oder
als Mail verschickt werden.

B<Routenbeschreibung in den Palm laden>

Folgendes gilt nur fE<uuml>r Unix-E<auml>hnliche Betriebssysteme.

In C<$PATH> muss sich mindestens eins der folgenden Programme
befinden: C<iSiloBSD>, C<iSiloLinux> oder C<pilot_makedoc>.

Die Sourcen zu C<pilot_makedoc> bekommt man z.B. bei

=over 4

=item *

L<ftp://ftp.forth.org/pub/PalmOS/>

=item *

L<ftp://ftp.cs.tu-berlin.de/pub/palmtops/pilot/>

=item *

L<ftp://ftp.cso.uiuc.edu/pub/systems/PalmOS/>

=back

C<iSilo> ist ein anderes Format, das einen speziellen Palm-Viewer
braucht, der allerdings HypertextfE<auml>hig ist. Die Binaries für die
Umwandlung findet man unter L<ftp://ftp.iSilo.com/pub/>. Hinweise zum
PalmViewer befinden sich auf der L<Homepage von iSilo|http://www.iSilo.com/>.

Die E<Uuml>bertragung erfolgt automatisch, wenn C<pilot-xfer> installiert
ist, welches man auf folgenden FTP-Servern bekommt:

=over 4

=item *

L<ftp://ryeham.ee.ryerson.ca/pub/PalmOS>

=item *

L<ftp://ftp.forth.org/pub/PalmOS/ryerson/>

=back

=item Route löschen

=for html <img src="images/cross.gif" alt="icon kreuz">

Mit Klick auf dieses Icon wird die aktuelle Route gelE<ouml>scht.

=item RE<uuml>ckweg-Symbol

=for html <img src="images/rueckweg.gif" alt="icon rueckweg">

Start- und Zielpunkt der aktuellen Route werden vertauscht.

=item Koordinaten-Symbol

=for html <img src="images/koord.gif" alt="icon koordinaten">

Dieses MenE<uuml> ist normalerweise nicht aktiviert und wird nur zum
Editieren der Koordinatendateien benE<ouml>tigt.

=item Info-Symbol

=for html <img src="images/info.gif" alt="icon information">

Hiermit kann im Informationsmodus umgeschaltet werden. Beim Klick auf
Kartenelemente wird jeweils ein Informationsfenster geE<ouml>ffnet.

Mit der C<i>-Taste kann das Informationsfenster für das Kartenelement
unter der Maus geöffnet werden.

Im Informationsfenster befinden sich Informationen zu: berechnete
Länge oder Fläche, Koordinaten in verschiedenen Koordinatensystemen
(WGS, GKK, UTM ...), Links zu der Web-Version von BBBike,
BBBike/Mapserver, Google Maps, Berliner Stadtplan (und weitere Links,
die durch Plugins bereitgestellt werden, z.B. durch das
LuiseBerlin-Plugin), Sonnenauf/untergang (benötigt das Perl-Modul
L<Astro::Sunrise>).

=item Karte verschieben

=for html <img src="images/movehand.gif" alt="icon hand">

Verschieben der Karte durch Ziehen der Maus

=item Salesman-Symbol

=for html <img src="images/salesman.gif" alt="icon handelsreisender">

(Dieses Symbol ist nur sichtbar, wenn das Salesman-Plugin geladen
wurde)

In diesem Modus kann die kE<uuml>rzeste Rundreise berechnet werden.
Dazu klickt man erst einmal in diesen Modus und wE<auml>hlt alle
gewE<uuml>nschten Stationen der Rundreise an. Der erste und letzte
Punkt werden fest als Start- und Zielpunkt markiert; alle anderen
Punkte werden in ihrer Reihenfolge frei gewE<auml>hlt. Wenn man alle
Stationen ausgewE<auml>hlt hat, muss man noch einmal auf das
Salesman-Symbol klicken, um die Berechnung zu starten. Es wird darauf
hingewiesen, dass bei einer groE<szlig>en Anzahl von Stationen (mehr
als acht) die Berechnung B<sehr> lange dauert (der geneigte Leser kann
sich die Problematik in der Literatur zum Thema "Problem des
Handlungsreisenden" bzw. "Traveling salesman problem" aneignen). Wenn
die Berechnung zu lange dauern wE<uuml>rde, kann sie mit der Esc-Taste
abgebrochen werden (wenn die Berechnung bereits mehr als zu 50%
durchgefE<uuml>hrt wurde, bekommt man dann noch ein Ergebnis, auch
wenn es nicht das optimalste ist).

=back

=head2 DATEIOPERATIONEN

=over 4

=item E<Ouml>ffnen-Symbol

=for html <img src="images/open.gif" alt="icon oeffnen">

Hiermit kann eine bereits gespeicherte Route wiedergeladen werden.
Eine Liste der zuletzt geladenen Routen kann man mit Klick auf die
rechte Maustaste erhalten.

ZusE<auml>tzlich zum bbbike-Format kann auch eine Track-Datei von
GPS-NavigationsgerE<auml>ten eingeladen werden. Die Datei muss aus
Zeilen im folgenden Format bestehen:


  TRK N52 29.072278 E13 15.879650 1998/06/21-08:47:20 1

=item Speichern-Symbol

=for html <img src="images/save.gif" alt="icon speichern">

Hiermit kann die aktuelle Route gespeichert werden.

MenE<uuml>:

Mit den MenE<uuml>punkten kann man den aktuellen Ausschnitt der Karte
als Bilddatei im B<Postscript>-, B<GIF>-, B<JPEG>- oder B<PPM>-Format
speichern speichern. GIF-Dateien sind in der Regel am kleinsten.
Postscript-Dateien sind vektororientiert und kE<ouml>nnen somit
beliebig ohne QualitE<auml>tsverluste vergrE<ouml>E<szlig>ert werden.
Das Erzeugen von JPEG- und PPM-Dateien ist normalerweise nicht
empfehlenswert.

Folgende Programme mE<uuml>ssen fE<uuml>r die verschiedenen Formate
installiert sein:


             |Postscript|  GIF  |  JPEG  |  PPM  |
  -----------+----------+-------+--------+-------+
  Ghostscript|    -     |   x   |    x   |   x   |
  pnmrotate  |    -     |   o   |    o   |   o   |
  ppmtogif   |    -     |   x   |    -   |   -   |
  cjpeg      |    -     |   -   |    x   |   -   |

(x = erforderlich, o = optional, - = nicht erforderlich)

Da der Postscript-Treiber, der fE<uuml>r jede Konvertierung aufgerufen
wird, die Schriften sehr klein darstellt, sollte im Orte-MenE<uuml>
der Punkt B<Sehr groE<szlig>e Schrift> gesetzt sein. Bessere
Ergebnisse erhE<auml>lt man, wenn man die Option -usexwd (xwd als
Screengrabber im Sonstiges-Teil des Optionseditors) einschaltet oder
direkt mit einem Screengrabber (z.B. B<xwd> oder B<xv>) arbeitet.

=item Drucken-Symbol

=for html <img src="images/printer.gif" alt="icon drucker">

Ausdruck des angezeigten Kartenausschnitts. Der Ausdruck wird nicht
direkt vorgenommen, sondern es wird eine Postscript-Datei erstellt und
ein Postscript-Viewer (z.B. B<gv> oder B<ghostview>) aufgerufen, aus
dem heraus gedruckt werden kann. Ist kein Postscript-Viewer vorhanden,
wird in eine temporE<auml>re Datei geschrieben.

MenE<uuml>:

=over 4

=item Farbe, Graustufen, Schwarz-WeiE<szlig>

Diese Schalter kontrollieren die Farbausgabe des Drucks.

=item Landscape, Portrait

Diese Schalter geben an, ob im Landscape- oder im Portrait-Modus
gedruckt werden soll. Im Portait-Modus erscheint die Karte verzerrt.

=item auf A4 skalieren

Wenn dieser Schalter aktiviert ist, wird die Karte so
vergrE<ouml>E<szlig>ert, dass ein A4-Blatt vollkommen
ausgefE<uuml>llt ist.

=item Legende

Eine Legende mit Nordpfeil wird mit ausgedruckt.

=item Legende rechts statt links

Die Position der Legende wird geE<auml>ndert.

=back

=back

=head2 WEITERE ICONS

=over 4

=item Fahrrad-Symbol (Bikepower)

=for html <img src="images/bicycle.gif" alt="icon fahrrad">

Aufruf des Bikepower-Moduls, z.B. zum Eintragen der persE<ouml>nlichen und
Fahrrad-Daten. Siehe L<BikePower|BikePower>.

=item Options-Symbol (O)

Hiermit kann der Options-Editor aufgerufen werden.

MenE<uuml>:

=over 4

=item Ausgabe sofort aktualisieren

Einige Kommandos wie B<Outline zeichnen> oder B<StraE<szlig>ennamen>
werden nicht sofort ausgefE<uuml>hrt, sondern beim nochmaligen
AnwE<auml>hlen des jeweiligen Icons. Um die sofortige Aktualisierung
zu erzwingen, kann dieser Schalter gesetzt werden.

=item Netz sofort aktualisieren

Hiermit wird die interne Darstellung des StraE<szlig>ennetzes
aktualisiert.

=item Alles aktualisieren

Alle ausstehenden Kommandos werden ausgefE<uuml>hrt.

=item gedrehte ZeichensE<auml>tze

Beim Zeichnen von StraE<szlig>en- und GewE<auml>ssernamen werden
gedrehte ZeichensE<auml>tze verwendet. Das Zeichnen wird dadurch
verlangsamt, auE<szlig>erdem wird der X-Server zusE<auml>tzlich
belastet.

Gedrehte ZeichensE<auml>tze kE<ouml>nnen nicht gedruckt werden.

=item Landscape

Die Karte wird im "Landscape"-Modus angezeigt.

=item Portrait

Die Karte wird im "Portrait"-Modus angezeigt.

=item Canvas balloon

Einschalten eines Balloons (Tooltip-Hilfe) fE<uuml>r den
Kartenbereich. Im UntermenE<uuml> kann zwischen B<kein> (kein
Balloon), B<nur Route> (Balloon wird nur E<uuml>ber einer Route
angezeigt) und B<E<uuml>berall> (Balloon wird E<uuml>ber allen
Kartenelementen angezeigt) ausgewE<auml>hlt werden.

=item Farben E<auml>ndern

Mit diesem MenE<uuml>punkt kE<ouml>nnen die Farben von B<bbbike>
geE<auml>ndert werden. Die E<Auml>nderungen sind nicht permanent.

=item Schriftart E<auml>ndern

Mit diesem MenE<uuml>punkt kann die Schriftart geE<auml>ndert werden.
Die E<Auml>nderung ist nicht permanent.

=item StE<auml>ndige Markierung

Wenn dieser Punkt eingeschaltet ist, bleibt die Markierung nach einer
Auswahl stehen, ansonsten blinkt die Markierung einige Male und wird
dann gelE<ouml>scht.

=item Markierung lE<ouml>schen

Falls B<StE<auml>ndige Markierung> eingeschaltet ist, kann eine
Markierung mit diesem MenE<uuml>punkt gelE<ouml>scht werden.

=item Status nach STDERR

Statusmeldungen werden nicht in der Statuszeile angezeigt, sondern
nach stderr umgelenkt.

=item Wortreich (verbose)

Es werden zusE<auml>tzliche Meldungen nach stderr ausgegeben.

=back

=item Hilfe-Symbol (?)

Anzeige der Online-Dokumentation (E<uuml>ber L<Tk::Pod|Tk::Pod> oder
einen WWW-Browser).

MenE<uuml>:

=over 4

=item Legende

Hiermit wird die Legende ein- und ausgeschaltet. In der Legende werden
nur die gerade angezeigten Kartenelemente erklärt. Tastatur: C<F1>.

=item Maushilfe

Ein Fenster mit den wichtigsten Mausbefehlen wird angezeigt.

=item Kontexthilfe

Schaltet die Kontexthilfe ein.

=item Netscape bbbike.html

Zeigt die BBBike-Dokumentation in Netscape an.

=item E<Uuml>ber...

Zeigt die Version von BBBike, perl und Tk an.

=item Busy-Zeiger zurE<uuml>cksetzen

Es kann vorkommen, dass nach einem Fehler der Busy-Zeiger (Uhr
oder Sandglas) nicht zurE<uuml>ckgesetzt wurde. Dies kann hiermit
nachgeholt werden.

=back

=item Kontexthilfe-Symbol

Mit der Kontexthilfe kann die Hilfe fE<uuml>r einen Button direkt
angefordert werden.

=item Ende-Symbol

Hiermit wird B<BBBike> beendet. TemporE<auml>re Dateien werden
gelE<ouml>scht und die Liste der zuletzt geE<ouml>ffnet Routen-Dateien
in C<~/.bbbike/last> gespeichert. Tastatur: C<Ctrl-q> oder C<Ctrl-C>.

=back

=head1 OPTIONEN

Folgende Kommandozeilenoptionen sind definiert:


    Usage: ./bbbike [options] --[no]str --[no]landstr --[no]sbahn
	--[no]sbahnhof --[no]ubahn --[no]ubahnhof --[no]rbahn --[no]rbahnhof
	--[no]wasser --[no]wasserumland --[no]wasserstadt --[no]faehre
	--[no]flaeche --[no]ort --[no]hs --[no]pp --outline --[no]ampel
	--lsamaybe --[no]plothoehe --[no]showgrade --[no]strname --[no]ortname
	--ortkategorie --[no]wassername --rbahnnetz --usbahnnetz
	--faraway --fast --turbo --lowmem --[no]diplom --[no]mldbm --center
	--centerc --edit --[no]qualitaetoptimierung --[no]qualitaetwerte
	--[no]kategorieoptimierung --[no]kategoriewerte --[no]sperre
	--[no]nichttragen --[no]ampeloptimierung --beschleunigung --[no]wind
	--[no]bikepwr --resetpower --power --resetspeed --speed --[no]www
	--[no]wwwmap --[no]wwwcache --cachedir --[no]wwwslow --proxy
	--[no]fontrot --fontfamily --fixedfontfamily --fontheight --fontweight
	--[no]balloon --[no]cballoon --cballoonwait --[no]contexthelp
	--[no]smoothscroll --[no]followmouse --[no]dialog --mapcolor
	--geometry --visual --scale --[no]overviewwasser --[no]flat
	--[no]transient --[no]autoscroll --autoscrollspeed --[no]audio
	--audiotype --coordout --printcmd --[no]gvreuse --[no]server
	--[no]autosave --[no]stderr --[no]advanced --[no]public -v --version
	-h

(Auswahl aus den Optionen:)

=over 4

=item --center strasse

Beim Starten wird auf die angegebene StraE<szlig>e zentriert.
Beispiel: C<--center Dudenstr>

=item --centerc koord

Beim Starten wird auf die angegebenen Koordinaten (Format "x,y")
zentriert.

=item --proxy httpproxy

Angabe eines Proxies fE<uuml>r WWW-Verbindungen im Format
"http://hostname:port/". Beispiel: C<http://www.cs.tu-berlin.de:80/>

=item routefile

Beim Starten wird die Routendatei geladen und angezeigt.

=back

=head1 ANFORDERUNGEN

FE<uuml>r das Zeichnen der realen Karten sind folgende Programme aus
dem pbmplus- bzw. netpbm-Paket notwendig:

=over 4

=item *

giftoppm

=item *

pnmscale

=item *

djpeg (aus libjpeg)

=back

Eine komplette Liste der optionalen perl-Module findet man in
L<Bundle::BBBike|Bundle::BBBike>.

=head1 INSTALLATION

=head2 Allgemein

Die Installationsbeschreibung befindet sich in der Datei
L<README|README> bzw. README.html. 

=head2 fvwm2

Bei der Verwendung von fvwm2 kE<ouml>nnen folgende Zeilen in .fvwm2rc
oder .fvwmrc eingefE<uuml>gt werden:

 Style "Bbbike*"        MiniIcon srtbike_mini.xpm
 Style "BbbikePassive"  GrabFocusOff, GrabFocusTransientOff

Die erste Zeile lE<auml>sst das BBBike-Icon in der Titelleiste
erscheinen. Dazu sollte die Datei srtbike_mini.xpm in ein Verzeichnis
eingefügt werden, wo sich die sonstigen fvwm-Icons befinden (siehe
Direktive PixmapPath). Die zweite Zeile sorgt dafE<uuml>r, dass
E<quot>unwichtigeE<quot> zusE<auml>tzliche Fenster nicht
(unnE<ouml>tigerweise) den Fokus erhalten.

=head1 BUGS

Zu viele...

=over 4

=item *

Entfernungen von manuell erzeugten Strecken werden bei der
Wegbeschreibung nicht berE<uuml>cksichtigt, wenn eine Neuberechnung
oder RE<uuml>ckweg angewE<auml>hlt wurde.

=item *

Suche: Das AnwE<auml>hlen eines Punktes innerhalb einer gesperrten
StraE<szlig>e ist fE<auml>lschlicherweise erlaubt. =E<gt> LE<ouml>sung:
mit inaccessible_streets feststellen, ob der Punkt (oder beide
Nachbarnpunkte) nicht erreicht werden kann und das AnwE<auml>hlen
verhindern.

=item *

optionadd...*search hat auch Auswirkungen auf den MenE<uuml>punkt in
Tk::Pod ... wie kann das begrenzt werden? Vielleicht MainWindow statt
Toplevel fE<uuml>r das Pod-Widget benutzen?

=item *

Beim Anzeigen einer Routenbeschreibung, die LandstraE<szlig>en
enthE<auml>lt, wird nichts ausgegeben, wenn LandstraE<szlig>en nicht
gezeichnet sind. => in nearest_points evtl. LandstraE<szlig>en bei
Bedarf nachladen (wie feststellen???).

=item *

Vias verschieben etc.: wenn eine Via-Flagge sich unterhalb eines
anderen Symbol befindet, kann es nicht angeklickt werden =E<gt>
LE<ouml>sung: Start,Via,Zielflagge bekommen ein zusE<auml>tzliches
Tag, das relativ weit hinten in stack_order steht.

=item *

Ab und zu, besonders beim Wechseln zwischen Kartenmodi, reagiert bbbike
beim Setzen eines Startpunktes nicht. Aushilfe: einmal "Route löschen"
auswählen, danach geht es wieder. =E<gt> scheint behoben zu sein
(siehe set_route_point, E<quot>XXX activatingE<quot>).

=back

=head1 LIMITATIONS

=over 4

=item *

Der Canvas-Postscript-Treiber kann mit rotierten Fonts nichts anfangen.

=back

=head1 TODO

Siehe L<TODO>.

=head1 KOMPATIBILITE<Auml>T

BBBike wird zur Zeit unter FreeBSD 6.1 mit perl 5.8.8
und den neuesten Perl/Tk-Versionen (z.Zt. 804.027+patches) entwickelt.

TestlE<auml>ufe wurden und werden von Zeit zu Zeit auf Windows
95/98/NT/2000/XP, Mac OS X und Linux (Debian 3.0, RedHat 8.0)
gefahren. Dabei werden meistens auch die aktuellen Stable-Versionen
von Perl und Tk verwendet.

Es wird versucht, auch zu der E<auml>lteren perl-Version 5.00503
kompatibel zu bleiben. Dabei könnten aber einige Features auf der
Strecke bleiben. Die GrundfunktionalitE<auml>t ist aber vorhanden.

perl 5.004 und älter sowie Tk 400 und älter wird nicht mehr
unterstützt. Für diese Versionen sollte ein älteres BBBike (Version
2.xx) verwendet werden.

=head1 ANERKENNUNG

TBD

=head1 AUTOR

Slaven Rezic - L<slaven@rezic.de|mailto:slaven@rezic.de>

=head1 PREREQUISITES

L<Tk|Tk>.

=head1 COREQUISITES

L<Tk::FireButton|Tk::FireButton>, L<Tk::Pod|Tk::Pod>,
L<LWP::UserAgent|LWP::UserAgent>, L<Mail::Send|Mail::Send> and many
others. See Makefile.PL or Bundle/BBBike.pm in the distribution for a
full list.

=head1 SEE ALSO

L<BikePower(3)|BikePower>, L<Tk(3)|Tk>, L<perl(1)|perl>.

=cut
