#!/usr/bin/env perl

# Find most crowded points in the simulation of 1000 routes in Berlin

open(my $handle, "<", "points") or die "Can't open points!";
#open(my $handle, "<", "bla") or die "Can't open points!";

my @points = ();

while (<$handle>) {
	my @point = split(', ', $_);
	push @points, [ @point ];
}

#print "Size of points: $#points\n";

my %count;
my %dups;
for my $point (@points) {
	$dummy = @$point[0] . "_" . @$point[1];
	#print $dummy . "\n";
	$dups{$dummy}++ if $count{$dummy}++;
}

$size = keys %dups;
print $size . "\n";

use Data::Dumper;
print Dumper(\%count);
