# -*- perl -*-
# DO NOT EDIT, generated by ../inline2dist.pl from StrassenNetz::CNetFile

package StrassenNetz::CNetFileDist;

package StrassenNetz::CNetFile;
require DynaLoader;
unshift @ISA, 'DynaLoader';
#use base 'DynaLoader';
$VERSION = "1.10";
use StrassenNetz::CNetFilePerl;

bootstrap StrassenNetz::CNetFile $VERSION;

1;
