### DO NOT EDIT! CREATED AUTOMATICALLY! ###
%define __prefix        %{_prefix}
Name: BBBike
Version: 3.06
Release: 19
Copyright: GPL
Group: Applications/Productivity
Requires: perl >= 5.005, perl-tk >= 800
Prefix: %{__prefix}
URL: http://bbbike.sourceforge.net
Packager: slaven@rezic.de
Source: http://prdownloads.sourceforge.net/bbbike/BBBike-3.06.tar.gz
Summary: A route-finder for cyclists in Berlin and Brandenburg

%description
A route-finder for cyclists in Berlin and Brandenburg.
Mit BBBike koennen Fahrrad-Routen in Berlin und Umgebung automatisch
oder manuell erstellt werden.
BBBike liefert unter anderem die Antwort auf folgende Fragen:
* Wie lang ist die Strecke von A nach B?
* Wie schnell komme ich von A nach B, wenn ich durchschnittlich 15
  km/h schnell fahre?
* Wie lange brauche ich von A nach B, wenn ich mit 100 Watt Leistung
  fahre, mit Beruecksichtigung des aktuellen Windes und von
  Steigungen auf der Strecke?
* Auf welchen Strassen fahre ich, wenn ich von A nach B kommen will?
* Wo habe ich Gegenwind- und Rueckenwindstrecken?
* Wo gibt es Steigungen und Gefaelle?
There is also a CGI script version available:
WWW: @BBBIKE_WWW@


%files
%{__prefix}/BBBike/Ampelschaltung.pm
%{__prefix}/BBBike/BBBikeAdvanced.pm
%{__prefix}/BBBike/BBBikeAlarm.pm
%{__prefix}/BBBike/BBBikeCalc.pm
%{__prefix}/BBBike/BBBikeDebug.pm
%{__prefix}/BBBike/BBBikeDraw.pm
%{__prefix}/BBBike/BBBikeDraw/GD.pm
%{__prefix}/BBBike/BBBikeDraw/PDF.pm
%{__prefix}/BBBike/BBBikeEdit.pm
%{__prefix}/BBBike/BBBikeEditUtil.pm
%{__prefix}/BBBike/BBBikeExp.pm
%{__prefix}/BBBike/BBBikeMail.pm
%{__prefix}/BBBike/BBBikeMenubar.pm
%{__prefix}/BBBike/BBBikePalm.pm
%{__prefix}/BBBike/BBBikePrint.pm
%{__prefix}/BBBike/BBBikeProfil.pm
%{__prefix}/BBBike/BBBikeServer.pm
%{__prefix}/BBBike/BBBikeTrans.pm
%{__prefix}/BBBike/BBBikeUtil.pm
%{__prefix}/BBBike/BBBikeVar.pm
%{__prefix}/BBBike/Bundle/BBBike.pm
%{__prefix}/BBBike/Bundle/BBBike_small.pm
%{__prefix}/BBBike/COPYING
%{__prefix}/BBBike/ESRI/Makefile.PL
%{__prefix}/BBBike/ESRI/Shapefile.pm
%{__prefix}/BBBike/ESRI/Shapefile/DBase.pm
%{__prefix}/BBBike/ESRI/Shapefile/Index.pm
%{__prefix}/BBBike/ESRI/Shapefile/Main.pm
%{__prefix}/BBBike/ESRI/esri2bbd.pl
%{__prefix}/BBBike/ESRI/t/shapefile.t
%{__prefix}/BBBike/FURadar.pm
%{__prefix}/BBBike/Fahrinfo.pm
%{__prefix}/BBBike/GIS/Globe.pm
%{__prefix}/BBBike/GIS/NSD.pm
%{__prefix}/BBBike/GIS/globe_to_bbd.pl
%{__prefix}/BBBike/GPS.pm
%{__prefix}/BBBike/GPS/G7toWin_ASCII.pm
%{__prefix}/BBBike/GPS/Unknown1.pm
%{__prefix}/BBBike/GPS/Unknown2.pm
%{__prefix}/BBBike/Geography.pm
%{__prefix}/BBBike/Geography/Berlin_DE.pm
%{__prefix}/BBBike/Geography/Muenchen_DE.pm
%{__prefix}/BBBike/GfxConvert.pm
%{__prefix}/BBBike/Hooks.pm
%{__prefix}/BBBike/Karte.pm
%{__prefix}/BBBike/Karte/Berlinmap1996.pm
%{__prefix}/BBBike/Karte/Berlinmap1997.pm
%{__prefix}/BBBike/Karte/Berlinmap1998.pm
%{__prefix}/BBBike/Karte/Berlinmap1999.pm
%{__prefix}/BBBike/Karte/Berlinmap2000.pm
%{__prefix}/BBBike/Karte/Berlinmap2001.pm
%{__prefix}/BBBike/Karte/FURadar.pm
%{__prefix}/BBBike/Karte/FURadar2.pm
%{__prefix}/BBBike/Karte/FURadar3.pm
%{__prefix}/BBBike/Karte/GDF.pm
%{__prefix}/BBBike/Karte/GIS.pm
%{__prefix}/BBBike/Karte/GISmap.pm
%{__prefix}/BBBike/Karte/GPS.pm
%{__prefix}/BBBike/Karte/Polar.pm
%{__prefix}/BBBike/Karte/Satmap.pm
%{__prefix}/BBBike/Karte/SatmapGIF.pm
%{__prefix}/BBBike/Karte/Soldner_alt.pm
%{__prefix}/BBBike/Karte/Standard.pm
%{__prefix}/BBBike/Karte/T99.pm
%{__prefix}/BBBike/MANIFEST
%{__prefix}/BBBike/Makefile.PL
%{__prefix}/BBBike/MasterPunkte.pm
%{__prefix}/BBBike/MasterStrassen.pm
%{__prefix}/BBBike/PLZ.pm
%{__prefix}/BBBike/PointEdit.pm
%{__prefix}/BBBike/README
%{__prefix}/BBBike/README.english
%{__prefix}/BBBike/README.english.html
%{__prefix}/BBBike/README.html
%{__prefix}/BBBike/RELEASE
%{__prefix}/BBBike/Radwege.pm
%{__prefix}/BBBike/Route.pm
%{__prefix}/BBBike/Salesman.pm
%{__prefix}/BBBike/Strassen.pm
%{__prefix}/BBBike/Strassen/ESRI.pm
%{__prefix}/BBBike/Strassen/Storable.pm
%{__prefix}/BBBike/Telefonbuch.pm
%{__prefix}/BBBike/Telefonbuch2001.pm
%{__prefix}/BBBike/Telefonbuch98.pm
%{__prefix}/BBBike/Telefonbuch99.pm
%{__prefix}/BBBike/Update.pm
%{__prefix}/BBBike/Way.pm
%{__prefix}/BBBike/Way/Metric.pm
%{__prefix}/BBBike/Wizards.pm
%{__prefix}/BBBike/bbbike
%{__prefix}/BBBike/bbbike-fast.bat
%{__prefix}/BBBike/bbbike.bat
%{__prefix}/BBBike/bbbike.html
%{__prefix}/BBBike/bbbike.pod
%{__prefix}/BBBike/bbbikeapplet
%{__prefix}/BBBike/bbbikeclient
%{__prefix}/BBBike/cbbbike
%{__prefix}/BBBike/cbbbike.bat
%{__prefix}/BBBike/cgi/BBBike_cgi_rare.pm
%{__prefix}/BBBike/cgi/README
%{__prefix}/BBBike/cgi/bbbike.cgi
%{__prefix}/BBBike/cgi/berlinmap.cgi
%{__prefix}/BBBike/cgi/httpi
%{__prefix}/BBBike/cgi/mksymlinks
%{__prefix}/BBBike/cgi/runbbbikecgi
%{__prefix}/BBBike/cgi/tinyhttpd
%{__prefix}/BBBike/cgi/wapbbbike.cgi
%{__prefix}/BBBike/cmdbbbike
%{__prefix}/BBBike/data/.modified
%{__prefix}/BBBike/data/Berlin.coords.data
%{__prefix}/BBBike/data/ampeln
%{__prefix}/BBBike/data/ampelschaltung
%{__prefix}/BBBike/data/berlin
%{__prefix}/BBBike/data/comments
%{__prefix}/BBBike/data/faehren
%{__prefix}/BBBike/data/flaechen
%{__prefix}/BBBike/data/gesperrt
%{__prefix}/BBBike/data/handicap_l
%{__prefix}/BBBike/data/handicap_s
%{__prefix}/BBBike/data/hoehe
%{__prefix}/BBBike/data/kinos
%{__prefix}/BBBike/data/kneipen
%{__prefix}/BBBike/data/kneipen-info
%{__prefix}/BBBike/data/label
%{__prefix}/BBBike/data/landstrassen
%{__prefix}/BBBike/data/landstrassen2
%{__prefix}/BBBike/data/multi_bez_str
%{__prefix}/BBBike/data/obst
%{__prefix}/BBBike/data/orte
%{__prefix}/BBBike/data/orte2
%{__prefix}/BBBike/data/orte_city
%{__prefix}/BBBike/data/plaetze
%{__prefix}/BBBike/data/plz
%{__prefix}/BBBike/data/qualitaet_l
%{__prefix}/BBBike/data/qualitaet_s
%{__prefix}/BBBike/data/radwege
%{__prefix}/BBBike/data/radwege_exact
%{__prefix}/BBBike/data/rbahn
%{__prefix}/BBBike/data/rbahnhof
%{__prefix}/BBBike/data/restaurants
%{__prefix}/BBBike/data/sbahn
%{__prefix}/BBBike/data/sbahnhof
%{__prefix}/BBBike/data/sehenswuerdigkeit
%{__prefix}/BBBike/data/sehenswuerdigkeit_img/brandenburger_tor.gif
%{__prefix}/BBBike/data/strassen
%{__prefix}/BBBike/data/ubahn
%{__prefix}/BBBike/data/ubahnhof
%{__prefix}/BBBike/data/umsteigebhf
%{__prefix}/BBBike/data/vorfahrt
%{__prefix}/BBBike/data/wasserstrassen
%{__prefix}/BBBike/data/wasserumland
%{__prefix}/BBBike/data/wasserumland2
%{__prefix}/BBBike/ext/BBBikeXS/BBBikeXS.pm
%{__prefix}/BBBike/ext/BBBikeXS/BBBikeXS.xs
%{__prefix}/BBBike/ext/BBBikeXS/MANIFEST
%{__prefix}/BBBike/ext/BBBikeXS/Makefile.PL
%{__prefix}/BBBike/ext/BBBikeXS/test.pl
%{__prefix}/BBBike/ext/BBBikeXS/typemap
%{__prefix}/BBBike/ext/VirtArray/Changes
%{__prefix}/BBBike/ext/VirtArray/MANIFEST
%{__prefix}/BBBike/ext/VirtArray/Makefile.PL
%{__prefix}/BBBike/ext/VirtArray/README
%{__prefix}/BBBike/ext/VirtArray/VirtArray.pm
%{__prefix}/BBBike/ext/VirtArray/VirtArray.xs
%{__prefix}/BBBike/ext/VirtArray/test.pl
%{__prefix}/BBBike/ext/VirtArray/typemap
%{__prefix}/BBBike/gnome/BBBikeDoc.tmpl
%{__prefix}/BBBike/gnome/BBBikeWWW
%{__prefix}/BBBike/gnome/bbbike.keys
%{__prefix}/BBBike/gnome/bbbike.mime
%{__prefix}/BBBike/html/allstreet.html
%{__prefix}/BBBike/html/bbbike.css
%{__prefix}/BBBike/html/bbbike_sidebar.html
%{__prefix}/BBBike/html/bbbike_small.en.html
%{__prefix}/BBBike/html/bbbike_small.html
%{__prefix}/BBBike/html/bbbike_start.js
%{__prefix}/BBBike/html/bbbikepod.css
%{__prefix}/BBBike/html/empty.html
%{__prefix}/BBBike/html/legende.html
%{__prefix}/BBBike/html/pleasewait.html
%{__prefix}/BBBike/html/presse.html
%{__prefix}/BBBike/images/abc.gif
%{__prefix}/BBBike/images/abc.xpm
%{__prefix}/BBBike/images/abc_hi.gif
%{__prefix}/BBBike/images/abc_hi.xpm
%{__prefix}/BBBike/images/add_ptr.xbm
%{__prefix}/BBBike/images/ampel.gif
%{__prefix}/BBBike/images/ampel.xpm
%{__prefix}/BBBike/images/ampel_klein.gif
%{__prefix}/BBBike/images/ampel_klein.png
%{__prefix}/BBBike/images/ampel_klein.xpm
%{__prefix}/BBBike/images/ampel_klein2.gif
%{__prefix}/BBBike/images/ampel_klein2.png
%{__prefix}/BBBike/images/ampel_klein2.xpm
%{__prefix}/BBBike/images/ampel_klein_grey.xpm
%{__prefix}/BBBike/images/andreaskr.gif
%{__prefix}/BBBike/images/andreaskr.xpm
%{__prefix}/BBBike/images/andreaskr_klein.gif
%{__prefix}/BBBike/images/andreaskr_klein.png
%{__prefix}/BBBike/images/andreaskr_klein.xpm
%{__prefix}/BBBike/images/andreaskr_klein2.gif
%{__prefix}/BBBike/images/andreaskr_klein2.png
%{__prefix}/BBBike/images/andreaskr_klein2.xpm
%{__prefix}/BBBike/images/apfel.gif
%{__prefix}/BBBike/images/apfel.xpm
%{__prefix}/BBBike/images/bbbike_splash.gif
%{__prefix}/BBBike/images/bbbike_splash.xpm
%{__prefix}/BBBike/images/bbbike_splash_oo.gif
%{__prefix}/BBBike/images/berlin_overview_small.gif
%{__prefix}/BBBike/images/berlin_overview_small.xpm
%{__prefix}/BBBike/images/berlin_small.gif
%{__prefix}/BBBike/images/berlin_small.xpm
%{__prefix}/BBBike/images/berlin_small_hi.gif
%{__prefix}/BBBike/images/berlin_small_hi.xpm
%{__prefix}/BBBike/images/bg.jpg
%{__prefix}/BBBike/images/bicycle.gif
%{__prefix}/BBBike/images/bicycle.xpm
%{__prefix}/BBBike/images/birne.gif
%{__prefix}/BBBike/images/birne.xpm
%{__prefix}/BBBike/images/bw_hleft.wbmp
%{__prefix}/BBBike/images/bw_hright.wbmp
%{__prefix}/BBBike/images/bw_left.wbmp
%{__prefix}/BBBike/images/bw_right.wbmp
%{__prefix}/BBBike/images/bw_straight.wbmp
%{__prefix}/BBBike/images/cgi_legende.gif
%{__prefix}/BBBike/images/cgi_legende.xpm
%{__prefix}/BBBike/images/click.gif
%{__prefix}/BBBike/images/click.xpm
%{__prefix}/BBBike/images/cross.gif
%{__prefix}/BBBike/images/cross.xpm
%{__prefix}/BBBike/images/delnet_ptr.xbm
%{__prefix}/BBBike/images/delnet_ptr_mask.xbm
%{__prefix}/BBBike/images/dest_ptr.xbm
%{__prefix}/BBBike/images/dest_ptr_mask.xbm
%{__prefix}/BBBike/images/essen.gif
%{__prefix}/BBBike/images/essen.xpm
%{__prefix}/BBBike/images/essen_klein.gif
%{__prefix}/BBBike/images/essen_klein.xpm
%{__prefix}/BBBike/images/exit.gif
%{__prefix}/BBBike/images/exit.xpm
%{__prefix}/BBBike/images/flaechen.gif
%{__prefix}/BBBike/images/flaechen.xpm
%{__prefix}/BBBike/images/flag2_bl.gif
%{__prefix}/BBBike/images/flag2_bl.png
%{__prefix}/BBBike/images/flag2_bl.xpm
%{__prefix}/BBBike/images/flag_ziel.gif
%{__prefix}/BBBike/images/flag_ziel.png
%{__prefix}/BBBike/images/flag_ziel.xpm
%{__prefix}/BBBike/images/gefaelle.gif
%{__prefix}/BBBike/images/gefaelle.xpm
%{__prefix}/BBBike/images/glas.gif
%{__prefix}/BBBike/images/glas.xpm
%{__prefix}/BBBike/images/glas_klein.gif
%{__prefix}/BBBike/images/glas_klein.xpm
%{__prefix}/BBBike/images/haltestelle.gif
%{__prefix}/BBBike/images/haltestelle.xpm
%{__prefix}/BBBike/images/help.gif
%{__prefix}/BBBike/images/help.xpm
%{__prefix}/BBBike/images/info.gif
%{__prefix}/BBBike/images/info.xpm
%{__prefix}/BBBike/images/info_ptr.xbm
%{__prefix}/BBBike/images/info_ptr_mask.xbm
%{__prefix}/BBBike/images/kino_klein.gif
%{__prefix}/BBBike/images/kino_klein.xpm
%{__prefix}/BBBike/images/kirsche.gif
%{__prefix}/BBBike/images/kirsche.xpm
%{__prefix}/BBBike/images/koord.gif
%{__prefix}/BBBike/images/koord.xpm
%{__prefix}/BBBike/images/landstrasse.gif
%{__prefix}/BBBike/images/landstrasse.xpm
%{__prefix}/BBBike/images/map.gif
%{__prefix}/BBBike/images/map.xpm
%{__prefix}/BBBike/images/menupfeil.gif
%{__prefix}/BBBike/images/menupfeil.xpm
%{__prefix}/BBBike/images/open.gif
%{__prefix}/BBBike/images/open.xpm
%{__prefix}/BBBike/images/opt.gif
%{__prefix}/BBBike/images/opt.xpm
%{__prefix}/BBBike/images/ort.gif
%{__prefix}/BBBike/images/ort.xpm
%{__prefix}/BBBike/images/pflaume.gif
%{__prefix}/BBBike/images/pflaume.xpm
%{__prefix}/BBBike/images/printer.gif
%{__prefix}/BBBike/images/printer.xpm
%{__prefix}/BBBike/images/rbahn.gif
%{__prefix}/BBBike/images/rbahn.xpm
%{__prefix}/BBBike/images/reddot.gif
%{__prefix}/BBBike/images/rueckweg.gif
%{__prefix}/BBBike/images/rueckweg.xpm
%{__prefix}/BBBike/images/salesman.gif
%{__prefix}/BBBike/images/salesman.xpm
%{__prefix}/BBBike/images/salesman_ptr.xbm
%{__prefix}/BBBike/images/salesman_ptr_mask.xbm
%{__prefix}/BBBike/images/save.gif
%{__prefix}/BBBike/images/save.xpm
%{__prefix}/BBBike/images/sbahn.gif
%{__prefix}/BBBike/images/sbahn.xpm
%{__prefix}/BBBike/images/search.gif
%{__prefix}/BBBike/images/search.xpm
%{__prefix}/BBBike/images/srtbike.gif
%{__prefix}/BBBike/images/srtbike.ico
%{__prefix}/BBBike/images/srtbike.jpg
%{__prefix}/BBBike/images/srtbike.png
%{__prefix}/BBBike/images/srtbike.xbm
%{__prefix}/BBBike/images/srtbike.xpm
%{__prefix}/BBBike/images/srtbike16.gif
%{__prefix}/BBBike/images/srtbike16.xpm
%{__prefix}/BBBike/images/srtbike32.gif
%{__prefix}/BBBike/images/srtbike32.xpm
%{__prefix}/BBBike/images/srtbike_mini.xpm
%{__prefix}/BBBike/images/srtbike_solid.gif
%{__prefix}/BBBike/images/srtbike_solid.xpm
%{__prefix}/BBBike/images/srtbike_www.ico
%{__prefix}/BBBike/images/srtbike_www.xpm
%{__prefix}/BBBike/images/start.gif
%{__prefix}/BBBike/images/start.xpm
%{__prefix}/BBBike/images/start_ptr.xbm
%{__prefix}/BBBike/images/start_ptr_mask.xbm
%{__prefix}/BBBike/images/steigung.gif
%{__prefix}/BBBike/images/steigung.xpm
%{__prefix}/BBBike/images/stip.xbm
%{__prefix}/BBBike/images/strasse.gif
%{__prefix}/BBBike/images/strasse.xpm
%{__prefix}/BBBike/images/strlist.gif
%{__prefix}/BBBike/images/strlist.xpm
%{__prefix}/BBBike/images/ubahn.gif
%{__prefix}/BBBike/images/ubahn.xpm
%{__prefix}/BBBike/images/usercross.gif
%{__prefix}/BBBike/images/usercross.xpm
%{__prefix}/BBBike/images/via.gif
%{__prefix}/BBBike/images/via.xpm
%{__prefix}/BBBike/images/viewmag+.gif
%{__prefix}/BBBike/images/viewmag+.xpm
%{__prefix}/BBBike/images/viewmag-.gif
%{__prefix}/BBBike/images/viewmag-.xpm
%{__prefix}/BBBike/images/vorfahrt.gif
%{__prefix}/BBBike/images/vorfahrt.xpm
%{__prefix}/BBBike/images/wasser.gif
%{__prefix}/BBBike/images/wasser.xpm
%{__prefix}/BBBike/images/watch_ptr.xbm
%{__prefix}/BBBike/images/watch_ptr_mask.xbm
%{__prefix}/BBBike/images/windrose.gif
%{__prefix}/BBBike/images/windrose.xpm
%{__prefix}/BBBike/images/windrose2.gif
%{__prefix}/BBBike/images/windrose2.xpm
%{__prefix}/BBBike/images/ziel.gif
%{__prefix}/BBBike/images/ziel.xpm
%{__prefix}/BBBike/images/ziel_ptr.xbm
%{__prefix}/BBBike/images/ziel_ptr_mask.xbm
%{__prefix}/BBBike/install.bat
%{__prefix}/BBBike/install.pl
%{__prefix}/BBBike/install.pl.config
%{__prefix}/BBBike/kde/BBBike.kdelnk.tmpl
%{__prefix}/BBBike/kde/BBBikeDoc.kdelnk.tmpl
%{__prefix}/BBBike/kde/BBBikeWWW.kdelnk
%{__prefix}/BBBike/kde/x-bbbike-data.kdelnk
%{__prefix}/BBBike/kde/x-bbbike-route.kdelnk
%{__prefix}/BBBike/kde/x-gpstrack.kdelnk
%{__prefix}/BBBike/lib/AutoInstall/Tk.pm
%{__prefix}/BBBike/lib/BikePower.pm
%{__prefix}/BBBike/lib/BikePower/HTML.pm
%{__prefix}/BBBike/lib/BikePower/Tk.pm
%{__prefix}/BBBike/lib/BikePower/change_wind.xpm
%{__prefix}/BBBike/lib/BikePower/crouch.xpm
%{__prefix}/BBBike/lib/BikePower/pack_end.xpm
%{__prefix}/BBBike/lib/BikePower/pack_middle.xpm
%{__prefix}/BBBike/lib/BikePower/racing.xpm
%{__prefix}/BBBike/lib/BikePower/standing.xpm
%{__prefix}/BBBike/lib/BikePower/tuck.xpm
%{__prefix}/BBBike/lib/BikePower/up_down.xpm
%{__prefix}/BBBike/lib/BikePower/upright.xpm
%{__prefix}/BBBike/lib/BrowserInfo.pm
%{__prefix}/BBBike/lib/Devel/WidgetDump.pm
%{__prefix}/BBBike/lib/EasySound.pm
%{__prefix}/BBBike/lib/GD/Wbmp.pm
%{__prefix}/BBBike/lib/Geometry.pm
%{__prefix}/BBBike/lib/Http.pm
%{__prefix}/BBBike/lib/KDEUtil.pm
%{__prefix}/BBBike/lib/Met/Wind.pm
%{__prefix}/BBBike/lib/Msg.pm
%{__prefix}/BBBike/lib/MyFile.pm
%{__prefix}/BBBike/lib/Text/ScriptTemplate.pm
%{__prefix}/BBBike/lib/Tk/Arrow.pm
%{__prefix}/BBBike/lib/Tk/Autoscroll.pm
%{__prefix}/BBBike/lib/Tk/BreakMenu.pm
%{__prefix}/BBBike/lib/Tk/CanvasBalloon.pm
%{__prefix}/BBBike/lib/Tk/CanvasExt.pm
%{__prefix}/BBBike/lib/Tk/ContextHelp.pm
%{__prefix}/BBBike/lib/Tk/Enscript.pm
%{__prefix}/BBBike/lib/Tk/FastSplash.pm
%{__prefix}/BBBike/lib/Tk/Fig.pm
%{__prefix}/BBBike/lib/Tk/FileDialogExt.pm
%{__prefix}/BBBike/lib/Tk/FlatCheckbox.pm
%{__prefix}/BBBike/lib/Tk/Getopt.pm
%{__prefix}/BBBike/lib/Tk/K2Listbox.pm
%{__prefix}/BBBike/lib/Tk/KListbox.pm
%{__prefix}/BBBike/lib/Tk/LayerEditor.pm
%{__prefix}/BBBike/lib/Tk/LayerEditorCore.pm
%{__prefix}/BBBike/lib/Tk/LayerEditorToplevel.pm
%{__prefix}/BBBike/lib/Tk/LogScale.pm
%{__prefix}/BBBike/lib/Tk/RaisedButton.pm
%{__prefix}/BBBike/lib/Tk/RotFont.pm
%{__prefix}/BBBike/lib/Tk/SRTProgress.pm
%{__prefix}/BBBike/lib/Tk/SRTScrollbar.pm
%{__prefix}/BBBike/lib/Tk/Splash.pm
%{__prefix}/BBBike/lib/Tk/StippleLine.pm
%{__prefix}/BBBike/lib/Tk/TextProgress.pm
%{__prefix}/BBBike/lib/Tk/UnderlineAll.pm
%{__prefix}/BBBike/lib/Tk/WListbox.pm
%{__prefix}/BBBike/lib/Tk/WidgetDump.pm
%{__prefix}/BBBike/lib/Tk/context_help.xbm
%{__prefix}/BBBike/lib/Tk/context_help_mask.xbm
%{__prefix}/BBBike/lib/Tk/context_nohelp.xbm
%{__prefix}/BBBike/lib/Tk/context_nohelp_mask.xbm
%{__prefix}/BBBike/lib/Tk/enscript.cfg
%{__prefix}/BBBike/lib/Tk/grid000.xbm
%{__prefix}/BBBike/lib/Tk/grid045.xbm
%{__prefix}/BBBike/lib/Tk/grid090.xbm
%{__prefix}/BBBike/lib/Tk/grid135.xbm
%{__prefix}/BBBike/lib/Tk/layereye.gif
%{__prefix}/BBBike/lib/Tk/resizeButton.pm
%{__prefix}/BBBike/lib/TkChange.pm
%{__prefix}/BBBike/lib/TkCompat.pm
%{__prefix}/BBBike/lib/UnixUtil.pm
%{__prefix}/BBBike/lib/WWWBrowser.pm
%{__prefix}/BBBike/lib/Waitproc.pm
%{__prefix}/BBBike/lib/Win32Util.pm
%{__prefix}/BBBike/lib/WinCompat.pm
%{__prefix}/BBBike/lib/click.au
%{__prefix}/BBBike/lib/click.wav
%{__prefix}/BBBike/lib/savevars.pm
%{__prefix}/BBBike/lib/wettermeldung2
%{__prefix}/BBBike/lib/your.pm
%{__prefix}/BBBike/msg/bbbike/en
%{__prefix}/BBBike/podindex.html
%{__prefix}/BBBike/smsbbbike
%{__prefix}/BBBike/tkbikepwr
%{__prefix}/BBBike/tmp/.keep_me

%post
rm -f %{_prefix}/bin/bbbike
ln -s %{_prefix}/BBBike/bbbike %{_prefix}/bin/bbbike

