### DO NOT EDIT! CREATED AUTOMATICALLY! ###
%define __prefix        %{_prefix}
Name: BBBike
Version: 3.15
Release: 5
Copyright: GPL
Group: Applications/Productivity
Requires: perl >= 5.005, perl-tk >= 800
Prefix: %{__prefix}
URL: http://bbbike.sourceforge.net
Packager: slaven@rezic.de
Source: http://heanet.dl.sourceforge.net/sourceforge/bbbike/BBBike-3.15.tar.gz
Summary: A route-finder for cyclists in Berlin and Brandenburg

%description
A route-finder for cyclists in Berlin and Brandenburg.
Mit BBBike koennen Fahrrad-Routen in Berlin und Umgebung automatisch
oder manuell erstellt werden.
BBBike liefert unter anderem die Antwort auf folgende Fragen:
* Wie lang ist die Strecke von A nach B?
* Wie schnell komme ich von A nach B, wenn ich durchschnittlich 15
  km/h schnell fahre?
* Wie lange brauche ich von A nach B, wenn ich mit 100 Watt Leistung
  fahre, mit Beruecksichtigung des aktuellen Windes und von
  Steigungen auf der Strecke?
* Auf welchen Strassen fahre ich, wenn ich von A nach B kommen will?
* Wo habe ich Gegenwind- und Rueckenwindstrecken?
* Wo gibt es Steigungen und Gefaelle?
WWW: @BBBIKE_SF_WWW@


%files
%{__prefix}/BBBike/Ampelschaltung.pm
%{__prefix}/BBBike/BBBikeAdvanced.pm
%{__prefix}/BBBike/BBBikeAlarm.pm
%{__prefix}/BBBike/BBBikeCalc.pm
%{__prefix}/BBBike/BBBikeCrosshairs.pm
%{__prefix}/BBBike/BBBikeDebug.pm
%{__prefix}/BBBike/BBBikeDraw.pm
%{__prefix}/BBBike/BBBikeDraw/GD.pm
%{__prefix}/BBBike/BBBikeDraw/GDHeavy.pm
%{__prefix}/BBBike/BBBikeDraw/ImageMagick.pm
%{__prefix}/BBBike/BBBikeDraw/Imager.pm
%{__prefix}/BBBike/BBBikeDraw/MapServer.pm
%{__prefix}/BBBike/BBBikeDraw/PDF.pm
%{__prefix}/BBBike/BBBikeDraw/SVG.pm
%{__prefix}/BBBike/BBBikeESRI.pm
%{__prefix}/BBBike/BBBikeEdit.pm
%{__prefix}/BBBike/BBBikeEditUtil.pm
%{__prefix}/BBBike/BBBikeGPS.pm
%{__prefix}/BBBike/BBBikeGlobalVars.pm
%{__prefix}/BBBike/BBBikeHeavy.pm
%{__prefix}/BBBike/BBBikeImportWizard.pm
%{__prefix}/BBBike/BBBikeLazy.pm
%{__prefix}/BBBike/BBBikeMail.pm
%{__prefix}/BBBike/BBBikeMapserver.pm
%{__prefix}/BBBike/BBBikeMenubar.pm
%{__prefix}/BBBike/BBBikeOvlPlugin.pm
%{__prefix}/BBBike/BBBikePalm.pm
%{__prefix}/BBBike/BBBikePersonal.pm
%{__prefix}/BBBike/BBBikePlugin.pm
%{__prefix}/BBBike/BBBikePrint.pm
%{__prefix}/BBBike/BBBikeProfil.pm
%{__prefix}/BBBike/BBBikeRouting.pm
%{__prefix}/BBBike/BBBikeRouting.pod
%{__prefix}/BBBike/BBBikeRuler.pm
%{__prefix}/BBBike/BBBikeSalesman.pm
%{__prefix}/BBBike/BBBikeScribble.pm
%{__prefix}/BBBike/BBBikeScribblePlugin.pm
%{__prefix}/BBBike/BBBikeServer.pm
%{__prefix}/BBBike/BBBikeStats.pm
%{__prefix}/BBBike/BBBikeThunder.pm
%{__prefix}/BBBike/BBBikeTrans.pm
%{__prefix}/BBBike/BBBikeUtil.pm
%{__prefix}/BBBike/BBBikeVar.pm
%{__prefix}/BBBike/BBBikeVia.pm
%{__prefix}/BBBike/BBBikeWeather.pm
%{__prefix}/BBBike/Bundle/BBBike.pm
%{__prefix}/BBBike/Bundle/BBBike_small.pm
%{__prefix}/BBBike/CHANGES
%{__prefix}/BBBike/COPYING
%{__prefix}/BBBike/ESRI/Makefile.PL
%{__prefix}/BBBike/ESRI/Shapefile.pm
%{__prefix}/BBBike/ESRI/Shapefile/DBase.pm
%{__prefix}/BBBike/ESRI/Shapefile/Index.pm
%{__prefix}/BBBike/ESRI/Shapefile/Main.pm
%{__prefix}/BBBike/ESRI/TODO
%{__prefix}/BBBike/ESRI/esri2bbd.pl
%{__prefix}/BBBike/ESRI/t/shapefile.t
%{__prefix}/BBBike/FURadar.pm
%{__prefix}/BBBike/Fahrinfo.pm
%{__prefix}/BBBike/GIS/Globe.pm
%{__prefix}/BBBike/GIS/NSD.pm
%{__prefix}/BBBike/GIS/globe_to_bbd.pl
%{__prefix}/BBBike/GPS.pm
%{__prefix}/BBBike/GPS/DirectGarmin.pm
%{__prefix}/BBBike/GPS/G7toWin_2.pm
%{__prefix}/BBBike/GPS/G7toWin_ASCII.pm
%{__prefix}/BBBike/GPS/Gardown.pm
%{__prefix}/BBBike/GPS/Gpsbabel.pm
%{__prefix}/BBBike/GPS/GpsmanConn.pm
%{__prefix}/BBBike/GPS/GpsmanData.pm
%{__prefix}/BBBike/GPS/MPS.pm
%{__prefix}/BBBike/GPS/MyNMEA.pm
%{__prefix}/BBBike/GPS/Ovl.pm
%{__prefix}/BBBike/GPS/SerialStty.pm
%{__prefix}/BBBike/GPS/Unknown1.pm
%{__prefix}/BBBike/GPS/Util.pm
%{__prefix}/BBBike/GPS/WaypointPlus.pm
%{__prefix}/BBBike/GPS/t/gpsmandata.t
%{__prefix}/BBBike/Geography.pm
%{__prefix}/BBBike/Geography/Berlin_DE.pm
%{__prefix}/BBBike/Geography/Brandenburg_DE.pm
%{__prefix}/BBBike/Geography/Muenchen_DE.pm
%{__prefix}/BBBike/GfxConvert.pm
%{__prefix}/BBBike/Hooks.pm
%{__prefix}/BBBike/HouseNumbers.pm
%{__prefix}/BBBike/Karte.pm
%{__prefix}/BBBike/Karte/Berlinmap1996.pm
%{__prefix}/BBBike/Karte/Berlinmap1997.pm
%{__prefix}/BBBike/Karte/Berlinmap1998.pm
%{__prefix}/BBBike/Karte/Berlinmap1999.pm
%{__prefix}/BBBike/Karte/Berlinmap2000.pm
%{__prefix}/BBBike/Karte/Berlinmap2001.pm
%{__prefix}/BBBike/Karte/Berlinmap2002.pm
%{__prefix}/BBBike/Karte/Berlinmap2003.pm
%{__prefix}/BBBike/Karte/Berlinmap2004.pm
%{__prefix}/BBBike/Karte/Cityinfo.pm
%{__prefix}/BBBike/Karte/Demap2002.pm
%{__prefix}/BBBike/Karte/ETRS89.pm
%{__prefix}/BBBike/Karte/FURadar.pm
%{__prefix}/BBBike/Karte/FURadar2.pm
%{__prefix}/BBBike/Karte/FURadar3.pm
%{__prefix}/BBBike/Karte/GDF.pm
%{__prefix}/BBBike/Karte/GIS.pm
%{__prefix}/BBBike/Karte/GISmap.pm
%{__prefix}/BBBike/Karte/GPS.pm
%{__prefix}/BBBike/Karte/Nbrbmap2004.pm
%{__prefix}/BBBike/Karte/PilotPl.pm
%{__prefix}/BBBike/Karte/PilotPl12.pm
%{__prefix}/BBBike/Karte/Polar.pm
%{__prefix}/BBBike/Karte/Potsdammap2002.pm
%{__prefix}/BBBike/Karte/Satmap.pm
%{__prefix}/BBBike/Karte/SatmapGIF.pm
%{__prefix}/BBBike/Karte/Soldner_alt.pm
%{__prefix}/BBBike/Karte/Standard.pm
%{__prefix}/BBBike/Karte/T2001.pm
%{__prefix}/BBBike/Karte/T99.pm
%{__prefix}/BBBike/Karte/Tk50.pm
%{__prefix}/BBBike/Karte/UTM.pm
%{__prefix}/BBBike/MANIFEST
%{__prefix}/BBBike/Makefile.PL
%{__prefix}/BBBike/MasterPunkte.pm
%{__prefix}/BBBike/MasterStrassen.pm
%{__prefix}/BBBike/PLZ.pm
%{__prefix}/BBBike/PLZ/Multi.pm
%{__prefix}/BBBike/PointEdit.pm
%{__prefix}/BBBike/README
%{__prefix}/BBBike/README.english
%{__prefix}/BBBike/README.english.html
%{__prefix}/BBBike/README.html
%{__prefix}/BBBike/Radwege.pm
%{__prefix}/BBBike/Route.pm
%{__prefix}/BBBike/Route/Descr.pm
%{__prefix}/BBBike/Route/Heavy.pm
%{__prefix}/BBBike/Route/PDF.pm
%{__prefix}/BBBike/Salesman.pm
%{__prefix}/BBBike/Strassen.pm
%{__prefix}/BBBike/Strassen/Build.pm
%{__prefix}/BBBike/Strassen/CDB.pm
%{__prefix}/BBBike/Strassen/Core.pm
%{__prefix}/BBBike/Strassen/CoreHeavy.pm
%{__prefix}/BBBike/Strassen/DB_File.pm
%{__prefix}/BBBike/Strassen/DB_File_Btree.pm
%{__prefix}/BBBike/Strassen/Dataset.pm
%{__prefix}/BBBike/Strassen/E00.pm
%{__prefix}/BBBike/Strassen/ESRI.pm
%{__prefix}/BBBike/Strassen/Edit.pm
%{__prefix}/BBBike/Strassen/Ext.pm
%{__prefix}/BBBike/Strassen/Fast.pm
%{__prefix}/BBBike/Strassen/FromRoute.pm
%{__prefix}/BBBike/Strassen/GPX.pm
%{__prefix}/BBBike/Strassen/Gardown.pm
%{__prefix}/BBBike/Strassen/Generated.pm
%{__prefix}/BBBike/Strassen/Generated_src.pm
%{__prefix}/BBBike/Strassen/Gpsman.pm
%{__prefix}/BBBike/Strassen/Heavy.pm
%{__prefix}/BBBike/Strassen/Kreuzungen.pm
%{__prefix}/BBBike/Strassen/Lazy.pm
%{__prefix}/BBBike/Strassen/MapInfo.pm
%{__prefix}/BBBike/Strassen/MultiBezStr.pm
%{__prefix}/BBBike/Strassen/MultiStrassen.pm
%{__prefix}/BBBike/Strassen/Obsolete.pm
%{__prefix}/BBBike/Strassen/Pg.pm
%{__prefix}/BBBike/Strassen/Stat.pm
%{__prefix}/BBBike/Strassen/Storable.pm
%{__prefix}/BBBike/Strassen/Strasse.pm
%{__prefix}/BBBike/Strassen/StrassenNetz.pm
%{__prefix}/BBBike/Strassen/StrassenNetzHeavy.pm
%{__prefix}/BBBike/Strassen/Tie.pm
%{__prefix}/BBBike/Strassen/Util.pm
%{__prefix}/BBBike/Strassen/WaypointPlus.pm
%{__prefix}/BBBike/TODO.pod
%{__prefix}/BBBike/Telefonbuch.pm
%{__prefix}/BBBike/Telefonbuch2001.pm
%{__prefix}/BBBike/Telefonbuch98.pm
%{__prefix}/BBBike/Telefonbuch99.pm
%{__prefix}/BBBike/TelefonbuchAny.pm
%{__prefix}/BBBike/Update.pm
%{__prefix}/BBBike/Way.pm
%{__prefix}/BBBike/Way/Metric.pm
%{__prefix}/BBBike/Wizards.pm
%{__prefix}/BBBike/bbbike
%{__prefix}/BBBike/bbbike-fast.bat
%{__prefix}/BBBike/bbbike.bat
%{__prefix}/BBBike/bbbike.html
%{__prefix}/BBBike/bbbike.pod
%{__prefix}/BBBike/bbbike_internals.html
%{__prefix}/BBBike/bbbike_internals.pod
%{__prefix}/BBBike/bbbikeapplet
%{__prefix}/BBBike/bbbikeclient
%{__prefix}/BBBike/bbd.html
%{__prefix}/BBBike/bbd.pod
%{__prefix}/BBBike/cbbbike
%{__prefix}/BBBike/cbbbike.bat
%{__prefix}/BBBike/cgi/README
%{__prefix}/BBBike/cgi/bbbike-data.cgi
%{__prefix}/BBBike/cgi/bbbike-teaser.pl
%{__prefix}/BBBike/cgi/bbbike.cgi
%{__prefix}/BBBike/cgi/bbbikegooglemap.cgi
%{__prefix}/BBBike/cgi/berlinmap.cgi
%{__prefix}/BBBike/cgi/configure-bbbike.cgi
%{__prefix}/BBBike/cgi/httpd.conf.tpl
%{__prefix}/BBBike/cgi/httpi
%{__prefix}/BBBike/cgi/mapserver_address.cgi
%{__prefix}/BBBike/cgi/mapserver_comment.cgi
%{__prefix}/BBBike/cgi/mapserver_setcoord.cgi
%{__prefix}/BBBike/cgi/mksymlinks
%{__prefix}/BBBike/cgi/redirect-bbbike.cgi
%{__prefix}/BBBike/cgi/runbbbikecgi
%{__prefix}/BBBike/cgi/tinyhttpd
%{__prefix}/BBBike/cgi/tinyhttpd.config
%{__prefix}/BBBike/cgi/wapbbbike.cgi
%{__prefix}/BBBike/cmdbbbike
%{__prefix}/BBBike/data/.modified
%{__prefix}/BBBike/data/Berlin.coords.data
%{__prefix}/BBBike/data/Potsdam.coords.data
%{__prefix}/BBBike/data/README
%{__prefix}/BBBike/data/ampeln
%{__prefix}/BBBike/data/ampelschaltung
%{__prefix}/BBBike/data/berlin
%{__prefix}/BBBike/data/brunnels
%{__prefix}/BBBike/data/comments_cyclepath
%{__prefix}/BBBike/data/comments_ferry
%{__prefix}/BBBike/data/comments_kfzverkehr
%{__prefix}/BBBike/data/comments_misc
%{__prefix}/BBBike/data/comments_mount
%{__prefix}/BBBike/data/comments_path
%{__prefix}/BBBike/data/comments_route
%{__prefix}/BBBike/data/comments_scenic
%{__prefix}/BBBike/data/comments_tram
%{__prefix}/BBBike/data/deutschland
%{__prefix}/BBBike/data/faehren
%{__prefix}/BBBike/data/flaechen
%{__prefix}/BBBike/data/fragezeichen
%{__prefix}/BBBike/data/gesperrt
%{__prefix}/BBBike/data/gesperrt_car
%{__prefix}/BBBike/data/gesperrt_r
%{__prefix}/BBBike/data/gesperrt_s
%{__prefix}/BBBike/data/gesperrt_u
%{__prefix}/BBBike/data/green
%{__prefix}/BBBike/data/handicap_l
%{__prefix}/BBBike/data/handicap_s
%{__prefix}/BBBike/data/hoehe
%{__prefix}/BBBike/data/housenumbers
%{__prefix}/BBBike/data/inaccessible_landstrassen
%{__prefix}/BBBike/data/inaccessible_strassen
%{__prefix}/BBBike/data/innerberliner_grenze
%{__prefix}/BBBike/data/kneipen
%{__prefix}/BBBike/data/label
%{__prefix}/BBBike/data/landstrassen
%{__prefix}/BBBike/data/landstrassen2
%{__prefix}/BBBike/data/mount
%{__prefix}/BBBike/data/multi_bez_str
%{__prefix}/BBBike/data/nolighting
%{__prefix}/BBBike/data/obst
%{__prefix}/BBBike/data/orte
%{__prefix}/BBBike/data/orte2
%{__prefix}/BBBike/data/orte_city
%{__prefix}/BBBike/data/plaetze
%{__prefix}/BBBike/data/plz
%{__prefix}/BBBike/data/potsdam
%{__prefix}/BBBike/data/qualitaet_l
%{__prefix}/BBBike/data/qualitaet_s
%{__prefix}/BBBike/data/radwege
%{__prefix}/BBBike/data/radwege_exact
%{__prefix}/BBBike/data/rbahn
%{__prefix}/BBBike/data/rbahnhof
%{__prefix}/BBBike/data/sbahn
%{__prefix}/BBBike/data/sbahnhof
%{__prefix}/BBBike/data/sbahnhof_bg
%{__prefix}/BBBike/data/sehenswuerdigkeit
%{__prefix}/BBBike/data/sehenswuerdigkeit_img/brandenburger_tor.gif
%{__prefix}/BBBike/data/sehenswuerdigkeit_img/fernsehturm.gif
%{__prefix}/BBBike/data/sehenswuerdigkeit_img/funkturm.gif
%{__prefix}/BBBike/data/sehenswuerdigkeit_img/gedaechtniskirche.gif
%{__prefix}/BBBike/data/sehenswuerdigkeit_img/luftbrueckendenkmal.gif
%{__prefix}/BBBike/data/sehenswuerdigkeit_img/oberbaumbruecke.gif
%{__prefix}/BBBike/data/sehenswuerdigkeit_img/oberbaumcity.gif
%{__prefix}/BBBike/data/sehenswuerdigkeit_img/reichstag.gif
%{__prefix}/BBBike/data/sehenswuerdigkeit_img/schultheiss.gif
%{__prefix}/BBBike/data/sehenswuerdigkeit_img/siegessaeule.gif
%{__prefix}/BBBike/data/sehenswuerdigkeit_img/viktoriaparkdenkmal.gif
%{__prefix}/BBBike/data/strassen
%{__prefix}/BBBike/data/strassen_bab
%{__prefix}/BBBike/data/ubahn
%{__prefix}/BBBike/data/ubahnhof
%{__prefix}/BBBike/data/ubahnhof_bg
%{__prefix}/BBBike/data/umsteigebhf
%{__prefix}/BBBike/data/vorfahrt
%{__prefix}/BBBike/data/wasserstrassen
%{__prefix}/BBBike/data/wasserumland
%{__prefix}/BBBike/data/wasserumland2
%{__prefix}/BBBike/ext/BBBikeXS/BBBikeXS.pm
%{__prefix}/BBBike/ext/BBBikeXS/BBBikeXS.xs
%{__prefix}/BBBike/ext/BBBikeXS/MANIFEST
%{__prefix}/BBBike/ext/BBBikeXS/Makefile.PL
%{__prefix}/BBBike/ext/BBBikeXS/README
%{__prefix}/BBBike/ext/BBBikeXS/sqrt.c
%{__prefix}/BBBike/ext/BBBikeXS/sqrt.h
%{__prefix}/BBBike/ext/BBBikeXS/t/base.t
%{__prefix}/BBBike/ext/BBBikeXS/t/leak.t
%{__prefix}/BBBike/ext/BBBikeXS/t/makenet.t
%{__prefix}/BBBike/ext/BBBikeXS/t/prefer_cache.t
%{__prefix}/BBBike/ext/BBBikeXS/t/strecke.t
%{__prefix}/BBBike/ext/BBBikeXS/t/to_koord1.t
%{__prefix}/BBBike/ext/BBBikeXS/typemap
%{__prefix}/BBBike/ext/Makefile
%{__prefix}/BBBike/ext/Strassen-Inline/Inline.pm
%{__prefix}/BBBike/ext/Strassen-Inline/InlineDist.pm
%{__prefix}/BBBike/ext/Strassen-Inline/Makefile.PL
%{__prefix}/BBBike/ext/Strassen-Inline/heap.c
%{__prefix}/BBBike/ext/Strassen-Inline/heap.h
%{__prefix}/BBBike/ext/Strassen-Inline/ppport.h
%{__prefix}/BBBike/ext/Strassen-Inline/t/common.pl
%{__prefix}/BBBike/ext/Strassen-Inline/t/db_impl.t
%{__prefix}/BBBike/ext/Strassen-Inline/t/hv_impl.t
%{__prefix}/BBBike/ext/Strassen-Inline2/Inline2.pm
%{__prefix}/BBBike/ext/Strassen-Inline2/Inline2Dist.pm
%{__prefix}/BBBike/ext/Strassen-Inline2/Makefile.PL
%{__prefix}/BBBike/ext/Strassen-Inline2/ppport.h
%{__prefix}/BBBike/ext/Strassen-Inline2/t/common.pl
%{__prefix}/BBBike/ext/Strassen-Inline2/t/db_impl.t
%{__prefix}/BBBike/ext/Strassen-Inline2/t/hv_impl.t
%{__prefix}/BBBike/ext/StrassenNetz-CNetFile/CNetFile.pm
%{__prefix}/BBBike/ext/StrassenNetz-CNetFile/CNetFileDist.pm
%{__prefix}/BBBike/ext/StrassenNetz-CNetFile/CNetFilePerl.pm
%{__prefix}/BBBike/ext/StrassenNetz-CNetFile/Makefile.PL
%{__prefix}/BBBike/ext/StrassenNetz-CNetFile/ppport.h
%{__prefix}/BBBike/ext/StrassenNetz-CNetFile/t/base.t
%{__prefix}/BBBike/ext/VectorUtil-Inline/Inline.pm
%{__prefix}/BBBike/ext/VectorUtil-Inline/Inline.xs
%{__prefix}/BBBike/ext/VectorUtil-Inline/InlineDist.pm
%{__prefix}/BBBike/ext/VectorUtil-Inline/Makefile.PL
%{__prefix}/BBBike/ext/VectorUtil-Inline/t/point_in_poly.t
%{__prefix}/BBBike/ext/VectorUtil-Inline/t/vectorutil.t
%{__prefix}/BBBike/ext/VirtArray/Changes
%{__prefix}/BBBike/ext/VirtArray/MANIFEST
%{__prefix}/BBBike/ext/VirtArray/Makefile.PL
%{__prefix}/BBBike/ext/VirtArray/README
%{__prefix}/BBBike/ext/VirtArray/VirtArray.pm
%{__prefix}/BBBike/ext/VirtArray/VirtArray.xs
%{__prefix}/BBBike/ext/VirtArray/test.pl
%{__prefix}/BBBike/ext/VirtArray/typemap
%{__prefix}/BBBike/ext/inline2dist.pl
%{__prefix}/BBBike/gnome/BBBikeDoc.tmpl
%{__prefix}/BBBike/gnome/BBBikeWWW
%{__prefix}/BBBike/gnome/bbbike.keys
%{__prefix}/BBBike/gnome/bbbike.mime
%{__prefix}/BBBike/html/allstreet.html
%{__prefix}/BBBike/html/bbbike.css
%{__prefix}/BBBike/html/bbbike_result.js
%{__prefix}/BBBike/html/bbbike_sidebar.en.html
%{__prefix}/BBBike/html/bbbike_sidebar.html
%{__prefix}/BBBike/html/bbbike_small.en.html
%{__prefix}/BBBike/html/bbbike_small.html
%{__prefix}/BBBike/html/bbbike_start.js
%{__prefix}/BBBike/html/bbbikepod.css
%{__prefix}/BBBike/html/bbbikeprint.css
%{__prefix}/BBBike/html/empty.html
%{__prefix}/BBBike/html/fragezeichenform.html
%{__prefix}/BBBike/html/help.html
%{__prefix}/BBBike/html/legende.html
%{__prefix}/BBBike/html/newstreetform.html
%{__prefix}/BBBike/html/newstreetform.tpl.html
%{__prefix}/BBBike/html/pleasewait.html
%{__prefix}/BBBike/html/presse.html
%{__prefix}/BBBike/html/sprintf.js
%{__prefix}/BBBike/images/PoweredByPerl.gif
%{__prefix}/BBBike/images/abc.gif
%{__prefix}/BBBike/images/abc.xpm
%{__prefix}/BBBike/images/abc_hi.gif
%{__prefix}/BBBike/images/abc_hi.xpm
%{__prefix}/BBBike/images/addnet_ptr.xbm
%{__prefix}/BBBike/images/addnet_ptr_mask.xbm
%{__prefix}/BBBike/images/airport.gif
%{__prefix}/BBBike/images/airport.xpm
%{__prefix}/BBBike/images/ampel.gif
%{__prefix}/BBBike/images/ampel.png
%{__prefix}/BBBike/images/ampel.xpm
%{__prefix}/BBBike/images/ampel_klein.gif
%{__prefix}/BBBike/images/ampel_klein.jpg
%{__prefix}/BBBike/images/ampel_klein.png
%{__prefix}/BBBike/images/ampel_klein.xpm
%{__prefix}/BBBike/images/ampel_klein2.gif
%{__prefix}/BBBike/images/ampel_klein2.jpg
%{__prefix}/BBBike/images/ampel_klein2.png
%{__prefix}/BBBike/images/ampel_klein2.xpm
%{__prefix}/BBBike/images/ampel_klein2_rahmen.gif
%{__prefix}/BBBike/images/ampel_klein2_rahmen.png
%{__prefix}/BBBike/images/ampel_klein2_rahmen.xpm
%{__prefix}/BBBike/images/ampel_klein_grey.xpm
%{__prefix}/BBBike/images/ampelf.gif
%{__prefix}/BBBike/images/ampelf.png
%{__prefix}/BBBike/images/ampelf.xpm
%{__prefix}/BBBike/images/ampelf_klein.gif
%{__prefix}/BBBike/images/ampelf_klein.png
%{__prefix}/BBBike/images/ampelf_klein.xpm
%{__prefix}/BBBike/images/ampelf_klein2.gif
%{__prefix}/BBBike/images/ampelf_klein2.png
%{__prefix}/BBBike/images/ampelf_klein2.xpm
%{__prefix}/BBBike/images/ampelf_klein_noalpha.png
%{__prefix}/BBBike/images/ampelf_noalpha.png
%{__prefix}/BBBike/images/andreaskr.gif
%{__prefix}/BBBike/images/andreaskr.png
%{__prefix}/BBBike/images/andreaskr.xpm
%{__prefix}/BBBike/images/andreaskr_klein.gif
%{__prefix}/BBBike/images/andreaskr_klein.jpg
%{__prefix}/BBBike/images/andreaskr_klein.png
%{__prefix}/BBBike/images/andreaskr_klein.xpm
%{__prefix}/BBBike/images/andreaskr_klein2.gif
%{__prefix}/BBBike/images/andreaskr_klein2.jpg
%{__prefix}/BBBike/images/andreaskr_klein2.png
%{__prefix}/BBBike/images/andreaskr_klein2.xpm
%{__prefix}/BBBike/images/apfel.gif
%{__prefix}/BBBike/images/apfel.png
%{__prefix}/BBBike/images/apfel.xpm
%{__prefix}/BBBike/images/bbbike_splash.gif
%{__prefix}/BBBike/images/bbbike_splash.xpm
%{__prefix}/BBBike/images/behindertenfreundlich.gif
%{__prefix}/BBBike/images/behindertengerecht.gif
%{__prefix}/BBBike/images/behindertengerecht_klein.gif
%{__prefix}/BBBike/images/behindertengerecht_klein2.gif
%{__prefix}/BBBike/images/berlin_overview_small.gif
%{__prefix}/BBBike/images/berlin_overview_small.xpm
%{__prefix}/BBBike/images/berlin_small.gif
%{__prefix}/BBBike/images/berlin_small.xpm
%{__prefix}/BBBike/images/berlin_small_hi.gif
%{__prefix}/BBBike/images/berlin_small_hi.xpm
%{__prefix}/BBBike/images/bg.gif
%{__prefix}/BBBike/images/bg.jpg
%{__prefix}/BBBike/images/bicycle.gif
%{__prefix}/BBBike/images/bicycle.xpm
%{__prefix}/BBBike/images/birne.gif
%{__prefix}/BBBike/images/birne.png
%{__prefix}/BBBike/images/birne.xpm
%{__prefix}/BBBike/images/bw_hleft.wbmp
%{__prefix}/BBBike/images/bw_hright.wbmp
%{__prefix}/BBBike/images/bw_left.wbmp
%{__prefix}/BBBike/images/bw_right.wbmp
%{__prefix}/BBBike/images/bw_straight.wbmp
%{__prefix}/BBBike/images/car.gif
%{__prefix}/BBBike/images/car.png
%{__prefix}/BBBike/images/car.xpm
%{__prefix}/BBBike/images/cgi_legende.gif
%{__prefix}/BBBike/images/cgi_legende.xpm
%{__prefix}/BBBike/images/church.gif
%{__prefix}/BBBike/images/church.png
%{__prefix}/BBBike/images/church.xpm
%{__prefix}/BBBike/images/click.gif
%{__prefix}/BBBike/images/click.xpm
%{__prefix}/BBBike/images/cross.gif
%{__prefix}/BBBike/images/cross.xpm
%{__prefix}/BBBike/images/crosses.xbm
%{__prefix}/BBBike/images/delete_ovl.gif
%{__prefix}/BBBike/images/delnet_ptr.xbm
%{__prefix}/BBBike/images/delnet_ptr_mask.xbm
%{__prefix}/BBBike/images/dest_ptr.xbm
%{__prefix}/BBBike/images/dest_ptr_mask.xbm
%{__prefix}/BBBike/images/essen.gif
%{__prefix}/BBBike/images/essen.xpm
%{__prefix}/BBBike/images/essen_klein.gif
%{__prefix}/BBBike/images/essen_klein.xpm
%{__prefix}/BBBike/images/exit.gif
%{__prefix}/BBBike/images/exit.xpm
%{__prefix}/BBBike/images/favicon.ico
%{__prefix}/BBBike/images/ferry.gif
%{__prefix}/BBBike/images/ferry.png
%{__prefix}/BBBike/images/ferry.xpm
%{__prefix}/BBBike/images/ferry_klein.gif
%{__prefix}/BBBike/images/ferry_klein.png
%{__prefix}/BBBike/images/ferry_klein.xpm
%{__prefix}/BBBike/images/flaechen.gif
%{__prefix}/BBBike/images/flaechen.xpm
%{__prefix}/BBBike/images/flag2_bl.gif
%{__prefix}/BBBike/images/flag2_bl.jpg
%{__prefix}/BBBike/images/flag2_bl.png
%{__prefix}/BBBike/images/flag2_bl.wbmp
%{__prefix}/BBBike/images/flag2_bl.xpm
%{__prefix}/BBBike/images/flag2_bl_centered.gif
%{__prefix}/BBBike/images/flag2_bl_centered.png
%{__prefix}/BBBike/images/flag2_bl_centered.xpm
%{__prefix}/BBBike/images/flag_via.gif
%{__prefix}/BBBike/images/flag_via.xpm
%{__prefix}/BBBike/images/flag_via_centered.gif
%{__prefix}/BBBike/images/flag_via_centered.png
%{__prefix}/BBBike/images/flag_via_centered.xpm
%{__prefix}/BBBike/images/flag_ziel.gif
%{__prefix}/BBBike/images/flag_ziel.jpg
%{__prefix}/BBBike/images/flag_ziel.png
%{__prefix}/BBBike/images/flag_ziel.xpm
%{__prefix}/BBBike/images/flag_ziel_centered.gif
%{__prefix}/BBBike/images/flag_ziel_centered.png
%{__prefix}/BBBike/images/flag_ziel_centered.xpm
%{__prefix}/BBBike/images/gefaelle.gif
%{__prefix}/BBBike/images/gefaelle.xpm
%{__prefix}/BBBike/images/glas.gif
%{__prefix}/BBBike/images/glas.xpm
%{__prefix}/BBBike/images/glas_klein.gif
%{__prefix}/BBBike/images/glas_klein.xpm
%{__prefix}/BBBike/images/haltestelle.gif
%{__prefix}/BBBike/images/haltestelle.xpm
%{__prefix}/BBBike/images/hatched_ring.gif
%{__prefix}/BBBike/images/hatched_ring.png
%{__prefix}/BBBike/images/hatched_ring.xpm
%{__prefix}/BBBike/images/help.gif
%{__prefix}/BBBike/images/help.xpm
%{__prefix}/BBBike/images/hospital.gif
%{__prefix}/BBBike/images/hospital.png
%{__prefix}/BBBike/images/hospital.xpm
%{__prefix}/BBBike/images/info.gif
%{__prefix}/BBBike/images/info.xpm
%{__prefix}/BBBike/images/info_ptr.xbm
%{__prefix}/BBBike/images/info_ptr_mask.xbm
%{__prefix}/BBBike/images/inwork.gif
%{__prefix}/BBBike/images/inwork.xpm
%{__prefix}/BBBike/images/kino_klein.gif
%{__prefix}/BBBike/images/kino_klein.xpm
%{__prefix}/BBBike/images/kirsche.gif
%{__prefix}/BBBike/images/kirsche.png
%{__prefix}/BBBike/images/kirsche.xpm
%{__prefix}/BBBike/images/koord.gif
%{__prefix}/BBBike/images/koord.xpm
%{__prefix}/BBBike/images/kopfstein_klein.gif
%{__prefix}/BBBike/images/kopfstein_klein.xpm
%{__prefix}/BBBike/images/kopfstein_klein_grey.gif
%{__prefix}/BBBike/images/kopfstein_klein_grey.xpm
%{__prefix}/BBBike/images/landstrasse.gif
%{__prefix}/BBBike/images/landstrasse.xpm
%{__prefix}/BBBike/images/legend_blocked.gif
%{__prefix}/BBBike/images/legend_blocked.png
%{__prefix}/BBBike/images/legend_blockedroute.gif
%{__prefix}/BBBike/images/legend_blockedroute.png
%{__prefix}/BBBike/images/legend_carry.gif
%{__prefix}/BBBike/images/legend_carry.png
%{__prefix}/BBBike/images/legend_narrowpassage.gif
%{__prefix}/BBBike/images/legend_narrowpassage.png
%{__prefix}/BBBike/images/legend_oneway.gif
%{__prefix}/BBBike/images/legend_oneway.png
%{__prefix}/BBBike/images/lightning.gif
%{__prefix}/BBBike/images/lightning_cursor.xbm
%{__prefix}/BBBike/images/map.gif
%{__prefix}/BBBike/images/map.xpm
%{__prefix}/BBBike/images/menupfeil.gif
%{__prefix}/BBBike/images/menupfeil.xpm
%{__prefix}/BBBike/images/minicross.png
%{__prefix}/BBBike/images/monument.gif
%{__prefix}/BBBike/images/monument.xpm
%{__prefix}/BBBike/images/moon.xpm
%{__prefix}/BBBike/images/mosque.gif
%{__prefix}/BBBike/images/mosque.png
%{__prefix}/BBBike/images/mosque.xpm
%{__prefix}/BBBike/images/movehand.gif
%{__prefix}/BBBike/images/movehand.xpm
%{__prefix}/BBBike/images/movehand_ptr.xbm
%{__prefix}/BBBike/images/movehand_ptr_mask.xbm
%{__prefix}/BBBike/images/newlayer.gif
%{__prefix}/BBBike/images/newlayer.png
%{__prefix}/BBBike/images/newlayer.xpm
%{__prefix}/BBBike/images/open.gif
%{__prefix}/BBBike/images/open.xpm
%{__prefix}/BBBike/images/open_ovl.gif
%{__prefix}/BBBike/images/opt.gif
%{__prefix}/BBBike/images/opt.xpm
%{__prefix}/BBBike/images/ort.gif
%{__prefix}/BBBike/images/ort.xpm
%{__prefix}/BBBike/images/pflaume.gif
%{__prefix}/BBBike/images/pflaume.png
%{__prefix}/BBBike/images/pflaume.xpm
%{__prefix}/BBBike/images/printer.gif
%{__prefix}/BBBike/images/printer.xpm
%{__prefix}/BBBike/images/ptr.xbm
%{__prefix}/BBBike/images/px_1t.gif
%{__prefix}/BBBike/images/radrouten.gif
%{__prefix}/BBBike/images/rbahn.gif
%{__prefix}/BBBike/images/rbahn.xpm
%{__prefix}/BBBike/images/redcross.gif
%{__prefix}/BBBike/images/redcross.png
%{__prefix}/BBBike/images/redcross.xpm
%{__prefix}/BBBike/images/reddot.gif
%{__prefix}/BBBike/images/rueckweg.gif
%{__prefix}/BBBike/images/rueckweg.xpm
%{__prefix}/BBBike/images/salesman.gif
%{__prefix}/BBBike/images/salesman.xpm
%{__prefix}/BBBike/images/salesman_ptr.xbm
%{__prefix}/BBBike/images/salesman_ptr_mask.xbm
%{__prefix}/BBBike/images/save.gif
%{__prefix}/BBBike/images/save.xpm
%{__prefix}/BBBike/images/sbahn.gif
%{__prefix}/BBBike/images/sbahn.jpg
%{__prefix}/BBBike/images/sbahn.png
%{__prefix}/BBBike/images/sbahn.xpm
%{__prefix}/BBBike/images/sbahn_klein.gif
%{__prefix}/BBBike/images/sbahn_klein.jpg
%{__prefix}/BBBike/images/sbahn_klein.png
%{__prefix}/BBBike/images/sbahn_klein.xpm
%{__prefix}/BBBike/images/sbahn_mini.gif
%{__prefix}/BBBike/images/sbahn_mini.jpg
%{__prefix}/BBBike/images/sbahn_mini.png
%{__prefix}/BBBike/images/sbahn_mini.xpm
%{__prefix}/BBBike/images/search.gif
%{__prefix}/BBBike/images/search.xpm
%{__prefix}/BBBike/images/search_pref.gif
%{__prefix}/BBBike/images/search_pref.xpm
%{__prefix}/BBBike/images/srtbike.gif
%{__prefix}/BBBike/images/srtbike.ico
%{__prefix}/BBBike/images/srtbike.jpg
%{__prefix}/BBBike/images/srtbike.png
%{__prefix}/BBBike/images/srtbike.xbm
%{__prefix}/BBBike/images/srtbike.xpm
%{__prefix}/BBBike/images/srtbike16.gif
%{__prefix}/BBBike/images/srtbike16.xpm
%{__prefix}/BBBike/images/srtbike16_mask.xbm
%{__prefix}/BBBike/images/srtbike32.gif
%{__prefix}/BBBike/images/srtbike32.xpm
%{__prefix}/BBBike/images/srtbike32_mask.xbm
%{__prefix}/BBBike/images/srtbike_mini.xpm
%{__prefix}/BBBike/images/srtbike_solid.gif
%{__prefix}/BBBike/images/srtbike_solid.xpm
%{__prefix}/BBBike/images/srtbike_url.png
%{__prefix}/BBBike/images/srtbike_www.ico
%{__prefix}/BBBike/images/srtbike_www.xpm
%{__prefix}/BBBike/images/star.gif
%{__prefix}/BBBike/images/star.png
%{__prefix}/BBBike/images/star.xpm
%{__prefix}/BBBike/images/start.gif
%{__prefix}/BBBike/images/start.xpm
%{__prefix}/BBBike/images/start_ptr.xbm
%{__prefix}/BBBike/images/start_ptr_mask.xbm
%{__prefix}/BBBike/images/steigung.gif
%{__prefix}/BBBike/images/steigung.png
%{__prefix}/BBBike/images/steigung.xpm
%{__prefix}/BBBike/images/stip.xbm
%{__prefix}/BBBike/images/stiplite.xbm
%{__prefix}/BBBike/images/strasse.gif
%{__prefix}/BBBike/images/strasse.xpm
%{__prefix}/BBBike/images/strlist.gif
%{__prefix}/BBBike/images/strlist.xpm
%{__prefix}/BBBike/images/synagogue.gif
%{__prefix}/BBBike/images/synagogue.png
%{__prefix}/BBBike/images/synagogue.xpm
%{__prefix}/BBBike/images/thunder_cursor.xbm
%{__prefix}/BBBike/images/touristinfo.gif
%{__prefix}/BBBike/images/touristinfo.png
%{__prefix}/BBBike/images/touristinfo.xpm
%{__prefix}/BBBike/images/ubahn.gif
%{__prefix}/BBBike/images/ubahn.jpg
%{__prefix}/BBBike/images/ubahn.png
%{__prefix}/BBBike/images/ubahn.xpm
%{__prefix}/BBBike/images/ubahn_klein.gif
%{__prefix}/BBBike/images/ubahn_klein.jpg
%{__prefix}/BBBike/images/ubahn_klein.png
%{__prefix}/BBBike/images/ubahn_klein.xpm
%{__prefix}/BBBike/images/ubahn_mini.gif
%{__prefix}/BBBike/images/ubahn_mini.jpg
%{__prefix}/BBBike/images/ubahn_mini.png
%{__prefix}/BBBike/images/ubahn_mini.xpm
%{__prefix}/BBBike/images/usercross.gif
%{__prefix}/BBBike/images/usercross.png
%{__prefix}/BBBike/images/usercross.xpm
%{__prefix}/BBBike/images/via.gif
%{__prefix}/BBBike/images/via.xpm
%{__prefix}/BBBike/images/via_add_nb1_ptr.xbm
%{__prefix}/BBBike/images/via_add_nb1_ptr_mask.xbm
%{__prefix}/BBBike/images/via_add_nb2_ptr.xbm
%{__prefix}/BBBike/images/via_add_nb2_ptr_mask.xbm
%{__prefix}/BBBike/images/via_add_ptr.xbm
%{__prefix}/BBBike/images/via_add_ptr_mask.xbm
%{__prefix}/BBBike/images/via_del_ptr.xbm
%{__prefix}/BBBike/images/via_del_ptr_mask.xbm
%{__prefix}/BBBike/images/via_move_2_ptr.xbm
%{__prefix}/BBBike/images/via_move_2_ptr_mask.xbm
%{__prefix}/BBBike/images/via_move_ptr.xbm
%{__prefix}/BBBike/images/via_move_ptr_mask.xbm
%{__prefix}/BBBike/images/viewmag+.gif
%{__prefix}/BBBike/images/viewmag+.xpm
%{__prefix}/BBBike/images/viewmag-.gif
%{__prefix}/BBBike/images/viewmag-.xpm
%{__prefix}/BBBike/images/vorfahrt.gif
%{__prefix}/BBBike/images/vorfahrt.xpm
%{__prefix}/BBBike/images/vorfahrt_klein.gif
%{__prefix}/BBBike/images/vorfahrt_klein.png
%{__prefix}/BBBike/images/vorfahrt_klein.xpm
%{__prefix}/BBBike/images/wasser.gif
%{__prefix}/BBBike/images/wasser.xpm
%{__prefix}/BBBike/images/watch_ptr.xbm
%{__prefix}/BBBike/images/watch_ptr_mask.xbm
%{__prefix}/BBBike/images/windrose.gif
%{__prefix}/BBBike/images/windrose.xpm
%{__prefix}/BBBike/images/windrose2.gif
%{__prefix}/BBBike/images/windrose2.xpm
%{__prefix}/BBBike/images/www_ptr.xbm
%{__prefix}/BBBike/images/www_ptr_mask.xbm
%{__prefix}/BBBike/images/xy_ptr.xbm
%{__prefix}/BBBike/images/xy_ptr_mask.xbm
%{__prefix}/BBBike/images/ziel.gif
%{__prefix}/BBBike/images/ziel.xpm
%{__prefix}/BBBike/images/ziel_ptr.xbm
%{__prefix}/BBBike/images/ziel_ptr_mask.xbm
%{__prefix}/BBBike/images/zugbruecke.gif
%{__prefix}/BBBike/images/zugbruecke.png
%{__prefix}/BBBike/images/zugbruecke.xpm
%{__prefix}/BBBike/images/zugbruecke_klein.gif
%{__prefix}/BBBike/images/zugbruecke_klein.png
%{__prefix}/BBBike/images/zugbruecke_klein.xpm
%{__prefix}/BBBike/install.bat
%{__prefix}/BBBike/install.pl
%{__prefix}/BBBike/install.pl.config
%{__prefix}/BBBike/kde/BBBike.kdelnk.tmpl
%{__prefix}/BBBike/kde/BBBikeDoc.kdelnk.tmpl
%{__prefix}/BBBike/kde/BBBikeWWW.kdelnk.tmpl
%{__prefix}/BBBike/kde/x-bbbike-data.kdelnk
%{__prefix}/BBBike/kde/x-bbbike-route.kdelnk
%{__prefix}/BBBike/kde/x-gpstrack.kdelnk
%{__prefix}/BBBike/lib/AutoInstall/Tk.pm
%{__prefix}/BBBike/lib/BikePower.pm
%{__prefix}/BBBike/lib/BikePower/HTML.pm
%{__prefix}/BBBike/lib/BikePower/Tk.pm
%{__prefix}/BBBike/lib/BikePower/change_wind.xpm
%{__prefix}/BBBike/lib/BikePower/crouch.xpm
%{__prefix}/BBBike/lib/BikePower/pack_end.xpm
%{__prefix}/BBBike/lib/BikePower/pack_middle.xpm
%{__prefix}/BBBike/lib/BikePower/racing.xpm
%{__prefix}/BBBike/lib/BikePower/standing.xpm
%{__prefix}/BBBike/lib/BikePower/tuck.xpm
%{__prefix}/BBBike/lib/BikePower/up_down.xpm
%{__prefix}/BBBike/lib/BikePower/upright.xpm
%{__prefix}/BBBike/lib/BrowserInfo.pm
%{__prefix}/BBBike/lib/BrowserInfo/UAProf.pm
%{__prefix}/BBBike/lib/Devel/WidgetDump.pm
%{__prefix}/BBBike/lib/GD/Convert.pm
%{__prefix}/BBBike/lib/Geometry.pm
%{__prefix}/BBBike/lib/Http.pm
%{__prefix}/BBBike/lib/KDEUtil.pm
%{__prefix}/BBBike/lib/Met/Wind.pm
%{__prefix}/BBBike/lib/Msg.pm
%{__prefix}/BBBike/lib/MyFile.pm
%{__prefix}/BBBike/lib/PDF/Create/MyPage.pm
%{__prefix}/BBBike/lib/Text/ScriptTemplate.pm
%{__prefix}/BBBike/lib/Tk/Arrow.pm
%{__prefix}/BBBike/lib/Tk/Autoscroll.pm
%{__prefix}/BBBike/lib/Tk/BreakMenu.pm
%{__prefix}/BBBike/lib/Tk/CanvasBalloon.pm
%{__prefix}/BBBike/lib/Tk/CanvasExt.pm
%{__prefix}/BBBike/lib/Tk/CanvasFig.pm
%{__prefix}/BBBike/lib/Tk/CanvasUtil.pm
%{__prefix}/BBBike/lib/Tk/ColorFlowChooser.pm
%{__prefix}/BBBike/lib/Tk/ContextHelp.pm
%{__prefix}/BBBike/lib/Tk/Enscript.pm
%{__prefix}/BBBike/lib/Tk/FastSplash.pm
%{__prefix}/BBBike/lib/Tk/FlatCheckbox.pm
%{__prefix}/BBBike/lib/Tk/FlatRadiobutton.pm
%{__prefix}/BBBike/lib/Tk/Getopt.pm
%{__prefix}/BBBike/lib/Tk/K2Listbox.pm
%{__prefix}/BBBike/lib/Tk/KListbox.pm
%{__prefix}/BBBike/lib/Tk/LayerEditor.pm
%{__prefix}/BBBike/lib/Tk/LayerEditorCore.pm
%{__prefix}/BBBike/lib/Tk/LayerEditorToplevel.pm
%{__prefix}/BBBike/lib/Tk/LogScale.pm
%{__prefix}/BBBike/lib/Tk/LongDialog.pm
%{__prefix}/BBBike/lib/Tk/PathEntry.pm
%{__prefix}/BBBike/lib/Tk/PathEntry/Dialog.pm
%{__prefix}/BBBike/lib/Tk/Placement.pm
%{__prefix}/BBBike/lib/Tk/ProgressSplash.pm
%{__prefix}/BBBike/lib/Tk/RaisedButton.pm
%{__prefix}/BBBike/lib/Tk/RotFont.pm
%{__prefix}/BBBike/lib/Tk/RotX11Font.pm
%{__prefix}/BBBike/lib/Tk/Ruler.pm
%{__prefix}/BBBike/lib/Tk/SRTProgress.pm
%{__prefix}/BBBike/lib/Tk/SRTScrollbar.pm
%{__prefix}/BBBike/lib/Tk/Splash.pm
%{__prefix}/BBBike/lib/Tk/StippleLine.pm
%{__prefix}/BBBike/lib/Tk/TextProgress.pm
%{__prefix}/BBBike/lib/Tk/UnderlineAll.pm
%{__prefix}/BBBike/lib/Tk/WListbox.pm
%{__prefix}/BBBike/lib/Tk/WidgetDump.pm
%{__prefix}/BBBike/lib/Tk/context_help.xbm
%{__prefix}/BBBike/lib/Tk/context_help_mask.xbm
%{__prefix}/BBBike/lib/Tk/context_nohelp.xbm
%{__prefix}/BBBike/lib/Tk/context_nohelp_mask.xbm
%{__prefix}/BBBike/lib/Tk/enscript.cfg
%{__prefix}/BBBike/lib/Tk/grid000.xbm
%{__prefix}/BBBike/lib/Tk/grid045.xbm
%{__prefix}/BBBike/lib/Tk/grid090.xbm
%{__prefix}/BBBike/lib/Tk/grid135.xbm
%{__prefix}/BBBike/lib/Tk/layereye.gif
%{__prefix}/BBBike/lib/Tk/resizeButton.pm
%{__prefix}/BBBike/lib/TkChange.pm
%{__prefix}/BBBike/lib/TkCompat.pm
%{__prefix}/BBBike/lib/UnixUtil.pm
%{__prefix}/BBBike/lib/VectorUtil.pm
%{__prefix}/BBBike/lib/WWWBrowser.pm
%{__prefix}/BBBike/lib/Waitproc.pm
%{__prefix}/BBBike/lib/Win32Util.pm
%{__prefix}/BBBike/lib/WinCompat.pm
%{__prefix}/BBBike/lib/click.au
%{__prefix}/BBBike/lib/click.wav
%{__prefix}/BBBike/lib/enum.pm
%{__prefix}/BBBike/lib/get_and_store_synop
%{__prefix}/BBBike/lib/parse_synop
%{__prefix}/BBBike/lib/savevars.pm
%{__prefix}/BBBike/lib/wettermeldung2
%{__prefix}/BBBike/lib/your.pm
%{__prefix}/BBBike/msg/bbbike/en
%{__prefix}/BBBike/msg/install/en
%{__prefix}/BBBike/podindex.html
%{__prefix}/BBBike/smsbbbike
%{__prefix}/BBBike/tkbikepwr
%{__prefix}/BBBike/tmp/.keep_me

%post
rm -f %{_prefix}/bin/bbbike
ln -s %{_prefix}/BBBike/bbbike %{_prefix}/bin/bbbike

