//=======================================================================
//@V@:Note: This file generated by vgen V1.02 (02:00:29 AM 17 May 1998).
//	vbbbikedlg.cpp:	Source for vbbbikeDialog class
//=======================================================================

#include "vbbbikedlg.h"
#include "vbbbikecmdw.h"
#include <v/vnotice.h>

//@V@:BeginIDs
    enum {
    lblMainMsg = 1000,
    strList = 1001,
    btnTestDlg		// add your id's here
  };
//@V@:EndIds

//@V@:BeginDialogCmd DefaultCmds
    static DialogCmd DefaultCmds[] =
      {
	{C_Label, lblMainMsg, 0,"X",NoList,CA_MainMsg,isSens,NoFrame, 0, 0},

	{C_List, strList, 0, "X",NoList,CA_None,isSens,NoFrame,0,lblMainMsg},

	{C_Button, M_Cancel, 0, " Cancel ",NoList,CA_None,
	    isSens,NoFrame,0, lblMainMsg},
	{C_Button, M_OK, 0, " OK ", NoList, CA_DefaultButton,
	    isSens, NoFrame, M_Cancel, lblMainMsg},

	{C_Button, btnTestDlg, 0, " Test ", NoList, CA_None,
	    isSens, NoFrame, M_OK, lblMainMsg},

	{C_EndOfList,0,0,0,0,CA_None,0,0,0}
    };
//@V@:EndDialogCmd


//=========================>>> vbbbikeDialog::vbbbikeDialog <<<====================
  vbbbikeDialog::vbbbikeDialog(vBaseWindow* bw, char* title) :
    vDialog(bw, 0, title)
  {
      UserDebug(Constructor,"vbbbikeDialog::vbbbikeDialog()\n")

    _myCmdWin = (vbbbikeCmdWindow*) bw;
    AddDialogCmds(DefaultCmds);		// add the predefined commands
  }

//========================>>> vbbbikeDialog::~vbbbikeDialog <<<====================
  vbbbikeDialog::~vbbbikeDialog()
  {
    UserDebug(Destructor,"vbbbikeDialog::~vbbbikeDialog() destructor\n")
  }

//====================>>> vbbbikeDialog::DialogCommand <<<=======================
  void vbbbikeDialog::DialogCommand(ItemVal id, ItemVal retval, CmdType ctype)
  {
    // Dialog commands to here

    UserDebug2(CmdEvents,"vbbbikeDialog::DialogCommand(id:%d, val:%d)\n",id, retval)

    switch (id)		// We will do some things depending on value
      {
	//@V@:Case: btnTestDlg
	case btnTestDlg:
	  {
	    vNoticeDialog note(this);
	    note.Notice("Test Dialog");
	    break;
	  }	//@V@:EndCase

      }

    vDialog::DialogCommand(id,retval,ctype);
  }

