=for comment -*- mode:pod; coding:utf-8; -*-

=encoding utf-8

=head1 AUTHOR

=over

=item * Slaven Rezić

Programmierung (Perl/Tk, Perl/CGI ...), Daten (Berlin, Uckermark,
Usedom ...)

=back

=head1 CONTRIBUTORS

=over

=item * Andreas Mühlhausen

Daten (Komplettierung innerhalb des Berliner Innenrings, Wilmersdorf,
Zehlendorf ...)

=item * Andreas Titz

Daten (von Oranienburg bis Hohen Neuendorf)

=item * and many more ...

=back

=cut
