=encoding utf-8

=head1 BBBike Internals

=head1 New Layers

The following changes are necessary:

=over

=item * Create data/I<layer>-orig file

=item * Add entry to data/BASE

=item * Add creation rule I<layer>-orig => I<layer> to data/Makefile.
List the rule in TARGETS

=item * Add check rules for I<layer> to data/Makefile, if appropriate.

=item * Add new layer to miscsrc/insert_points

=item * Add new files to MANIFEST

=item * Define a new abbreviation for I<layer> (C<$abk>) and use this
abbreviation in the following bbbike definitions: C<%tag_group>,
C<%category_color> ..., C<%str_file> and/or C<%p_file>,
C<@normal_stack_order>, array in C<set_bindings>, C<enterpoint>
handling.

=back

=head1 INTERNA

Verwendete Tags:

=over 4

=item Kreuzungen:

'pp', Koordinate (x,y), undef, pp-$abk

=item Strecken:

$abk, Name, $abk-$category, $abk-$index

=item Strecken (Outline):

$abk-out, $abk-$category-out

=item FlE<auml>chen:

$abk, Name

=item FlE<auml>chen (Outline):

$abk-out

=item besondere Punkte (BahnhE<ouml>fe etc.)

$abk-[fb]g, Name

$abk-[fb]g, Koordinate (x,y)

=item Ampeln

$abk-fg, Koordinate (x,y), Kategorie

=item Markierung Punkt:

'show', 'showp'

=item Markierung Strecke:

'show', 'shows'

=item Ort

'o', Name

=item Ort (Bezeichnung)

'O'

=item Route, Routenstartpunkt

'route', route-$nr

=item Karte

'map'

=back

=head1 AUTHOR

Slaven Rezic <srezic@cpan.org>

=head1 COPYRIGHT

Copyright (c) 2004 Slaven Rezic. All rights reserved.
This module is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=head1 SEE ALSO

L<bbbike>.
