=head1 Links rund um das Radrouting

=head2 Radwege und -touren

=head3 Fernradwege und Radtouren im Raum Brandenburg

=over

=item
L<http://www.das-rad-ruft.de/Radtouren/index.php?Bundesland=11&id=431&action=Suche>

GPS-Tracks in Brandenburg (Fernradwege und Benutzertouren)

=comment Last check and update (BRB,B,MV,SN): 2005-12-31

=item L<http://www.spreeradweg.de/>

Der Spreeradweg

=item L<http://www.bike-berlin-copenhagen.com/>

Berlin-Kopenhagen

=item L<http://www.berlin-usedom-radweginfo.de/>

Berlin-Usedom

=item L<http://www.teamdochnoch.de/mtb-barnim/MTBB_11.html>

Anfahrtsbeschreibung für Berlin-Usedom

=item L<http://www.havelland-radweg.de/>

Havelland-Radweg

=item L<http://www.brandenburg.adfc.de/Tourismus/index.htm>

Radfernwege in Brandenburg

=item
L<http://www.wirtschaft.brandenburg.de/sixcms/media.php/1312/broschurrad.pdf>

Broschüre der Landesregierung Brandenburg zum Thema Radrouten

=item
L<http://www.maerkisch-oderland.de/landratsamt/bauplanungsamt/Radwege2002.pdf>

Radwegkonzept in Märkisch-Oderland (MOL)

=item L<http://www.mediapur.de/foto_rad.html>

Radtouren um Bestensee (südlich von Königs Wusterhausen) herum

=item L<http://www.stechlin.de/aktivitaet.htm>

Radwege um den Stechlinsee (zwischen Rheinsberg und Fürstenberg) herum

=item
L<http://www.grass-net.de/modules.php?name=Content&pa=showpage&pid=16>

Radtouren im Südberliner Bereich von Sebastian Graß, Site nicht mehr
erreichbar!

=item L<http://www.radatlas.de/>

Radfernwege in ganz Deutschland. Für Brandenburg/Berlin eher wenig
Informationen.

=back

=head3 Radrouten und -touren im Raum Potsdam

=over

=item L<http://www.werder-havel.de/t2.htm>

Radrouten im Raum Potsdam

=item L<http://www.f-monzer-co.de/easteuro/hhklinik.htm>

Radtouren im Raum Potsdam

=item L<http://www.mobil-potsdam.de/radfahren.htm>

Radfahren - Mobil in Potsdam

=item L<http://www.hotel-zur-insel.de/images/radtour.pdf>

Otto-Lilienthal-Radtour (Havelland) (Link von
L<http://www.hotel-zur-insel.de/index.php?sec=rad> aus)

=back

=head3 Sonstiges

=over

=item L<http://www.radweit.de>

Tourenvorschläge mit Karten

=item L<http://www.achim-bartoschek.de/bahn_bb.htm>

Bahntrassenradeln

=comment Last check and update: 2005-12-31

=item L<http://www.malume.de/trackmanager/>

Tauschbörse für Tracks, Routen & Waypoints, allerdings keine in Berlin
und Brandenburg vorhanden

=comment Last check: 2005-12-31

=item
L<http://www.berliner-rundfunk.de/cgi-bin/WebObjects/brf.woa/wa/CMSshow/1058650>

Allgemeines zu Radtouren

=item
L<http://www.arur.de/rolandsreiseberichte.html>

Rolands Fahrradreisen (Berlin - Frankfurt, Oder, Berlin - Wien ...;
mit Tracks); weitere Radreiseberichte von anderen Leuten

=back

=head2 Verkehrsmeldungen

Alle Verkehrsmeldungsdienste sind primär für den Kfz-Verkehr gedacht,
aber einige Meldungen sind auch radfahrerrelevant (z.B.
Vollsperrungen).

=over

=item L<http://www.vmz-berlin.de/vmz/rdstmc.do>

Vehrkehrsmanagmentzentrale Berlin (VMZ)

=item
L<http://www.berlinonline.de/verkehrsticker/_bin/polizei-faxabruf.php>

Meldungen der Polizei (Berlin)

=item L<http://www.ls.brandenburg.de/>

Verkehrsmeldungen für Brandenburg

=item L<http://www.oepnv-berlin.de/news/news_aktuell.htm>,
L<http://www.bahninfo.de>

Meldungen für den öffentlichen Nahverkehr

=back

=head2 Fahrradrelevantes

=over

=item L<http://www.upi-institut.de/upi41.htm>

Straßenbeschaffenheit und Energieverbrauch beim Radfahren

=back

=head2 Fahrradroutenplaner

=over

=item

München (auf der Basis von BBBike): 
L<http://dream.lrrl.arch.tu-muenchen.de/cgi-bin/radl.cgi>

=back

=head2 Straßenverzeichnisse

=over

=item L<http://www.luise-berlin.de>

Komplettes Straßenverzeichnis von Berlin

=item
L<http://userpage.chemie.fu-berlin.de/diverse/doc/umbenennungen.html>

Umbenennungen in Berlin

=item L<http://www.britzer-buergerverein.de/archiv/strassen.htm>

Straßenverzeichnis von Britz

=back

=head2 Karten online

=over

=item L<http://fbinter.stadt-berlin.de/fb/index.jsp>

Verschiedene thematische Karten

=item L<http://www.berliner-stadplan.com>

Stadtplan auf Basis von Pharus-Stadtplänen

=item L<http://www.alt-berlin.info>

Historische Berliner Karten

=item L<http://www.stadtplandienst.de>

=back

=head2 Programmiersprachen

=over

=item L<http://www.perl.org>

Perl

=item L<http://www.activeperl.com>

ActivePerl von ActiveState für Windows. Kann alternativ statt des
mitgelieferten SiePerl für BBBike verwendet werden.

=item L<http://www.cpan.org>

Perl-Module @ CPAN

=back

=head2 Geodatenformate

=over

=item L<http://www.topografix.com/gpx_resources.asp>

GPX ist ein XML-basiertes Format für GPS-Routen, -Tracks und
-Waypoints.

=item L<http://gpsbabel.sourceforge.net/>

Ein Programm zum Konvertieren zwischen GPS-Formaten

=back

=head2 Waypoints und Tracks

=over

=item L<http://www.grabo.de/gps/index.html>

=item L<http://www.berlin-usedom-radweginfo.de/downloadzaehler.php?URL=http://www.berlin-usedom-radweginfo.de/tracks/0u1_BB.zip>

Ein Teil von Berlin-Usedom

=item L<http://adfc.jgr.de/alternativradroute/>,
L<http://adfc.jgr.de/alternativradroute/alternativradroute.ovl>

Alternativroute von Frankfurt/Oder Richtung Norden


=back

=head2 Meteorologie

=over

=item L<http://www.met.fu-berlin.de/de/wetter/wetterbeobachtung/>,
L<http://www.met.fu-berlin.de/de/wetter/wetterdaten/>

Wettermeldungen der FU Berlin

=item L<http://www.wetteronline.de>

Unter anderem Karten von Niederschlagradarechos mitsamt Animation.

=item
L<http://www.dwd.de/scripts/getimg.php?src=/wundk/Warnungen/DL00_O.png>

Unwetterwarnungskarte des Deutschen Wetterdienstes

=item L<http://www.nws.noaa.gov/om/windchill/>

Neue Formel zum Berechnen des Windchills.

=item L<http://puma.dkrz.de/theomet/prognosen/>,
L<http://puma.dkrz.de/theomet/prognosen/bilder/colorpop6.jpg>,
L<http://puma.dkrz.de/theomet/prognosen/bilder/colorpop6_12.jpg>

Niederschlagsprognosen

=item L<http://www.einfalt.de/x_rad_vorher.html>

Kommerzielles Programm für Niederschlagsprognosen

=back

=head2 Sonstiges

=over

=item
L<http://www.stadtentwicklung.berlin.de/umwelt/stadtgruen/kinderspielplaetze/de/spielplaetze/>

Spielplätze in Berlin

=item
L<http://homepage.schleswig-holstein.de/u_pahlke/basics/dictionary.htm>

geographische Begriffe (Wörterbuch Deutsch-Englisch)

=item L<http://www.statistik-berlin.de/framesets/berl4.htm>

Bezirke und Ortsteile in Berlin

=item L<http://www.suedwestbezirk.de/insel.html>

Fähren in Berlin

=item
L<http://www.stadtentwicklung.berlin.de/aktuell/pressebox/archiv.shtml>

Berlin, Senatsverwaltung für Stadtentwicklung, Pressearchiv (u.a. von
verkehrsrelevanten Baumaßnahmen)

=back

=head1 AUTHOR

Slaven Rezic <srezic@cpan.org>
