Watch Sites for BBBike						-*- org -*-

URLs, die immer wieder neue Informationen enthalten können.

* Berlin
** <2018-09-28 Fr> <2018-09-28 Fr> http://www.berlin.de/presse/pressemitteilungen/index/search?searchtext=&boolean=0&startdate=&enddate=&institutions%5B%5D=Senatsverwaltung+f%C3%BCr+Stadtentwicklung+und+Wohnen&institutions%5B%5D=Senatsverwaltung+f%C3%BCr+Umwelt%2C+Verkehr+und+Klimaschutz&institutions%5B%5D=Bezirksamt+Charlottenburg-Wilmersdorf&institutions%5B%5D=Bezirksamt+Friedrichshain-Kreuzberg&institutions%5B%5D=Bezirksamt+Lichtenberg&institutions%5B%5D=Bezirksamt+Marzahn-Hellersdorf&institutions%5B%5D=Bezirksamt+Mitte&institutions%5B%5D=Bezirksamt+Neuk%C3%B6lln&institutions%5B%5D=Bezirksamt+Pankow&institutions%5B%5D=Bezirksamt+Reinickendorf&institutions%5B%5D=Bezirksamt+Spandau&institutions%5B%5D=Bezirksamt+Steglitz-Zehlendorf&institutions%5B%5D=Bezirksamt+Tempelhof-Sch%C3%B6neberg&institutions%5B%5D=Bezirksamt+Treptow-K%C3%B6penick&bt=Suchen
   Sammelsuche mit allen Berliner Bezirken + Stadtentwicklung Berlin

   Früher benutzte Such-URL:
   http://www.berlin.de/pressemitteilungen/archiv/index/search?searchtext=&boolean=0&startdate=&enddate=&institutions[]=Senatsverwaltung+f%C3%BCr+Stadtentwicklung+und+Umwelt&institutions[]=Bezirksamt+Charlottenburg-Wilmersdorf&institutions[]=Bezirksamt+Friedrichshain-Kreuzberg&institutions[]=Bezirksamt+Lichtenberg&institutions[]=Bezirksamt+Marzahn-Hellersdorf&institutions[]=Bezirksamt+Mitte&institutions[]=Bezirksamt+Neuk%C3%B6lln&institutions[]=Bezirksamt+Pankow&institutions[]=Bezirksamt+Reinickendorf&institutions[]=Bezirksamt+Spandau&institutions[]=Bezirksamt+Steglitz-Zehlendorf&institutions[]=Bezirksamt+Tempelhof-Sch%C3%B6neberg&institutions[]=Bezirksamt+Treptow-K%C3%B6penick&bt=Suchen
** <2018-09-28 Fr> <2018-09-28 Fr> http://www.berlin.de/landesverwaltungsamt/logistikservice/amtsblatt-fuer-berlin/ bzw. http://amtsblatt.berlin.de

   Amtsblätter Berlin

   bereits überprüft:
   * in 2018:
     * 1..39
   * in 2017:
     * 1..56 (alles)
       (20 enthält den Berliner Mietspiegel)
       (33 enthält nur Wahlvorschläge)
       (41 enthält Ausführungsvorschriften bzgl. des FNP)
       (54 enthält die neuen VBB-Tarife)
   * in 2016:
     * 1..58 (alles)
       (32 enthält nur Wahlvorschläge)
       (34 enthält Ausführungsvorschriften bzgl. des FNP)
       (41 enthält Ausführungsvorschriften über schulische Prüfungen)
       (45 enthält die Ergebnisse der Wahl)
       (52 enthält ein Verzeichnis der Krankenhäuser)
       (56 enthält die neuen VBB-Tarife)
   * in 2015:
     * 1..53 (alles)
       (20 enthält den Berliner Mietspiegel)
       (52 enthält die neuen VBB-Tarife)
   * in 2014:
     * 1..54 (alles)
       (23 enthält ein Verzeichnis der Krankenhäuser)
       (53 enthält die neuen VBB-Tarife)
   * in 2013:
     * 1..56 (alles)
       (21 enthält den Berliner Mietspiegel)
       (24 enthält ein Verzeichnis der Krankenhäuser)
       (32 enthält die neuen VBB-Tarife)
       (35 enthält nur Wahlvorschläge)
   * in 2012:
     * 1..54 (alles)
       (23 enthält ein Verzeichnis der Krankenhäuser)
   * in 2011:
     * 1..57 (alles)
       (34 enthält nur Wahlvorschläge)
       (46 enthält die Ergebnisse der Wahl)
   * in 2010:
     * 34..54 (Ende)

   Alte URL (bis Ende 2016): http://www.kulturbuch-verlag.de/Service/amtsblatt-fur-berlin/kostenloser-lese-service
   Linkformat: http://www.kulturbuch-verlag.de/Service/amtsblatt-fur-berlin/kostenloser-lese-service/pdfl/{nummer}re.pdf/file

   Früher: "IMPORTANT!!! Use the ?y=2014 hack!!!"

* Potsdam
** <2018-05-18 Fr> <2018-04-26 Do> http://www.potsdam.de/kategorie/amtsblaetter Potsdamer Amtsblätter
   bereits überprüft:
   * 2018: 1..5
   * 2017: 1..13 (alle)
   * 2016: 1..12 (alle)
   * 2015: 1..14 (alle)
   * 2014: 1..16 (alle) frühere URL: http://www.potsdam.de/cms/ziel/2027173/DE/
   * 2013: 1..17 (alle) http://www.potsdam.de/cms/ziel/1771576/DE/
   * 2012: 1..17 (alle) http://www.potsdam.de/cms/ziel/1471008/DE/
   * 2011: 1..18 (alle) http://www.potsdam.de/cms/ziel/1189396/DE/
   * 2010: 1..16 (alle)
   * 2009: 1..20 (alle)
   * 2008: 4, 26

   Nicht überprüft: die Tagesordnungen der
   Stadtverordnetenversammlungen (wobei es hier wohl keine
   Ausführungsbeschlüsse gibt?)
** <2011-04-02 Sa> <2011-04-01 Fr> http://www.potsdam.de/cms/ziel/1191938/DE/ Pressemitteilungen in Potsdam
   Überprüfte Nachrichten: ab 2007-06-01
** <2017-11-20 Mo> <2017-11-20 Mo> http://www.mobil-potsdam.de/de/fahrrad/infos-zum-radverkehr/ Informationen zum Radverkehr
   früher: http://www.potsdam.de/cms/ziel/996205/DE/ FahrRad in Potsdam
   Seite existiert seit März 2014 nicht mehr. Nachfolgeseite evtl.
   http://www.mobil-potsdam.de/fahrrad_2_1.htm, aber hier keine
   aktuellen Informationen.
* Sonstige Themen
** <2018-09-29 Sa> <2018-09-29 Sa> http://www.berliner-woche.de/verkehr/
   Ab Anfang 2017 durchgesehen.
** <2018-09-29 Sa> <2018-09-29 Sa> http://www.berliner-woche.de/bauen/
   Ab Anfang 2017 durchgesehen
** <2018-09-21 Fr> <2018-09-03 Mo> http://www.stadtteilausschuss-kreuzberg.de/projekt18.htm
   * 2018:
     * Friesenstr.
** <2018-09-21 Fr> <2018-04-14 Sa> https://twitter.com/berlin_bau
   Frühere Adresse: https://www.facebook.com/pg/baustellen.berlin/posts/
** <2018-09-21 Fr> <2017-04-08 Sa> http://forum.koepenick.net/viewforum.php?f=2
   Köpenicker Themen (früher berlinforen.de)
** <2010-06-06 So> http://www.nationaler-radverkehrsplan.de/neuigkeiten/?kid=25
   Nationaler Radverkehrsplan, Neuigkeiten in Berlin
** <2010-01-27 Mi> http://www.nationaler-radverkehrsplan.de/neuigkeiten/?kid=36
   Nationaler Radverkehrsplan, Neuigkeiten in Brandenburg
* Software
** <2018-09-21 Fr> <2017-11-02 Do> http://portsmon.freebsd.org/portoverview.py?category=german&portname=BBBike 
   Status des BBBike-FreeBSD-Packages
   [2018-01-10 Mi] Seit ein paar Monaten ist diese Seite kaputt...
* BA-Beschlüsse
** <2018-05-07 Mo> <2018-02-20 Di> https://www.berlin.de/ba-charlottenburg-wilmersdorf/politik/bezirksamt/beschluesse/5-wahlperiode/
   Durchgeschaut: ab 05.01.2016
** <2018-05-07 Mo> <2018-04-24 Di> http://www.berlin.de/ba-friedrichshain-kreuzberg/politik-und-verwaltung/bezirksamt/sitzungen/2018/
   Die BA-Beschlüsse sind evtl. bereits im BVV-Informationssystem
   vollständig einsehbar.
   
   Beginn der Protokolle: <2012-12-04 Di>
** <2018-05-07 Mo> <2018-04-17 Di> http://www.berlin.de/ba-lichtenberg/politik-und-verwaltung/bezirksamt/protokolle/2018/

   26.04.2016 - ... angeschaut

   16.10.2012 - 12.02.2013 angeschaut

   Bis 2011 gab es die Beschlüsse hier:
   http://www.berlin.de/ba-lichtenberg/politik/bezirksamt-beschluesse.html
   15.11.2011 - 6.12.2011 --- wird anscheinend nicht mehr
   aktualisiert?

   Alte URL (bis 2015): http://www.berlin.de/ba-lichtenberg/politik/bezirksamt-protokolle.html
** <2018-05-07 Mo> <2018-04-24 Di> http://www.berlin.de/ba-marzahn-hellersdorf/politik-und-verwaltung/bezirksamt/beschluesse/2018/

   Ab 2016-01-12 ... angeschaut.

   ... bis 2013-02-05 angeschaut.

   Für das Jahr 2012:
   http://www.berlin.de/ba-marzahn-hellersdorf/politik/beschluesse/archiv2012.html
   Bereits durchgesehen: 30..51. BA-Sitzung 2012
** <2018-05-07 Mo> <2018-04-24 Di> http://www.berlin.de/ba-mitte/politik-und-verwaltung/bezirksamt/beschluesse-des-bezirksamts/2018/

   2016-01-05 - ... durchgeschaut.

   ... - 2014-02-18 durchgeschaut.

   Seit <2013-09-03 Di> werden BA-Beschlüsse veröffentlicht.
** <2018-05-07 Mo> <2018-01-30 Di> http://www.berlin.de/ba-neukoelln/politik-und-verwaltung/bezirksamt/beschluesse-des-bezirksamtes/artikel.669862.php

   Alle durchgeschaut.

   Seit <2015-06-23 Di> werden BA-Beschlüsse veröffentlicht.

   URL für 2016:
   http://www.berlin.de/ba-neukoelln/politik-und-verwaltung/bezirksamt/beschluesse-des-bezirksamtes/artikel.434089.php
** <2018-05-07 Mo> <2018-04-17 Di> http://www.berlin.de/ba-pankow/politik-und-verwaltung/bezirksamt/beschluesse-des-bezirksamts/2018/artikel.677679.php

   2016-01-05 - ... durchgeschaut.

   ... - 2013-01-22 durchgeschaut.

   ab 30.10.12

   URL für 2016:
   http://www.berlin.de/ba-pankow/politik-und-verwaltung/bezirksamt/beschluesse-des-bezirksamts/2016/artikel.434211.php
** <2018-05-07 Mo> <2018-01-16 Di> http://www.berlin.de/ba-reinickendorf/politik-und-verwaltung/bezirksamt/beschluesse-des-bezirksamtes/
   2016-01-05 - ... durchgeschaut

   Beschlüsse sind selten.
** <2018-05-07 Mo> <2018-04-17 Di> https://www.berlin.de/ba-spandau/politik-und-verwaltung/bezirksamt/beschluesse-des-bezirksamtes/2018/artikel.665237.php
   Beschlüsse ab Januar 2016 durchgeschaut.

   URL für 2016:
   https://www.berlin.de/ba-spandau/politik-und-verwaltung/bezirksamt/beschluesse-des-bezirksamtes/2016/artikel.436649.php
** <2018-05-07 Mo> <2018-02-27 Di> http://www.berlin.de/ba-steglitz-zehlendorf/politik-und-verwaltung/bezirksamt/protokolle/
   Ab 5.7.2016 durchgeschaut (nicht mehr, weil nicht informativ genug)

   ALte URL: http://www.berlin.de/ba-steglitz-zehlendorf/politik-und-verwaltung/bezirksamt/beschluesse-des-bezirksamtes/
** <2018-05-07 Mo> <2017-05-16 Di> http://www.berlin.de/ba-tempelhof-schoeneberg/politik-und-verwaltung/bezirksamt/beschluesse/simple-search/?q=&jahr=2017&betreff=&beschluss=&anlage1=&anlage2=&anlage3=&anlage4=&ipp=100#searchresults

   ACHTUNG: Das Datum "2017-08-17" für den letzten Beschluss ist
   vermutlich ein Tippfehler, der "2017-01-17" erscheint
   wahrscheinlicher.

   2016-01-12 - ... durchgeschaut

   ... - 2013-08-27 durchgeschaut

   Bereits durchgesehen: ab 17.7.2012 - ...

   [2013-11-22 Fr] Irgendwie sind die Beschlüsse der letzten Monate
   zwar aufgelistet, aber der Link auf die PDF-Datei fehlt...

   [2018-02-13 Di] URL für 2016:
   http://www.berlin.de/ba-tempelhof-schoeneberg/politik-und-verwaltung/bezirksamt/beschluesse/simple-search/?q=&jahr=2016&betreff=&beschluss=&anlage1=&anlage2=&anlage3=&anlage4=&ipp=20&order=&page=1#searchresults
** <2018-05-07 Mo> <2018-04-10 Di> http://www.berlin.de/ba-treptow-koepenick/politik-und-verwaltung/bezirksamt/beschluesse/simple-search/?q=&jahr=2018&ba_sitzung_from=&ba_sitzung_to=&ipp=100#searchresults

   2016-01-05 - ... durchgesehen

   ... - 2013-05-28 durchgesehen

   ab 12.06.2012
   evtl. neue/zusätzliche URL:
   http://www.berlin.de/ba-treptow-koepenick/politik/ba-beschluesse/simplesearch/index.php
   (gibt es nicht mehr)

   URL für 2016:
   http://www.berlin.de/ba-treptow-koepenick/politik-und-verwaltung/bezirksamt/beschluesse/simple-search/?q=&jahr=2016&ba_sitzung_from=&ba_sitzung_to=&ipp=20#searchresults
* Aktuelle Baumaßnahmen in den Bezirken
  Prioritäten = Informationsgehalt, Aktualisierungsrate
** <2017-05-22 Mo>              Charlottenburg fehlt
   frühere URL: http://www.berlin.de/ba-charlottenburg-wilmersdorf/org/tiefbau/fahrbahnsanierungen.html
   letzte Aktualisierung <2013-07-17 Mi>
** <2018-09-21 Fr> <2018-06-05 Di> [#C] http://www.berlin.de/ba-friedrichshain-kreuzberg/politik-und-verwaltung/aemter/strassen-und-gruenflaechenamt/artikel.205944.php
** <2018-09-21 Fr> <2018-07-12 Do> [#C] http://www.berlin.de/ba-friedrichshain-kreuzberg/politik-und-verwaltung/aemter/strassen-und-gruenflaechenamt/gruenflaechen/baumassnahmen/artikel.273777.php
** <2017-05-22 Mo>              Lichtenberg fehlt
** <2016-09-19 Mo>              Marzahn-Hellersdorf fehlt
** <2017-05-22 Mo>              Mitte fehlt
** <2018-09-21 Fr> <2018-08-27 Mo> [#B] https://www.berlin.de/ba-neukoelln/politik-und-verwaltung/aemter/strassen-und-gruenflaechenamt/strassen-und-verwaltung/strassenneubau/artikel.274070.php
** <2018-09-21 Fr> <2018-06-06 Mi> [#B] http://www.berlin.de/ba-pankow/verwaltung/tiefbau/strassenbau.html
** <2018-09-21 Fr> <2018-08-24 Fr> [#B] http://www.berlin.de/ba-pankow/politik-und-verwaltung/aemter/strassen-und-gruenflaechenamt/aktuelles/
** <2018-09-21 Fr> <2018-08-27 Mo> [#A] http://www.berlin.de/ba-reinickendorf/politik-und-verwaltung/aemter/strassen-und-gruenflaechenamt/strassenbau/artikel.129276.php
   Mit detaillierten Bauplänen.
   Evtl. monatliche Aktualisierung.
   Alte URL: http://www.berlin.de/ba-reinickendorf/org/strassenbau/baumassnahmen.html
** <2018-09-21 Fr> <2018-04-04 Mi> [#B] http://www.berlin.de/ba-spandau/politik-und-verwaltung/aemter/strassen-und-gruenflaechenamt/tiefbau/artikel.264598.php
   Zuletzt am 20.12.2016 keine einzige Meldung.
** <2018-09-21 Fr> <2017-05-09 Di> [#B] http://www.berlin.de/ba-steglitz-zehlendorf/politik-und-verwaltung/aemter/strassen-und-gruenflaechenamt/tiefbau/artikel.94904.php
   Mit detaillierten Bauplänen.
   Alte URL: http://www.berlin.de/ba-steglitz-zehlendorf/verwaltung/bauen/tiefbau/bauarbeiten.html
** <2018-09-21 Fr> <2017-05-09 Di> [#B] http://www.berlin.de/ba-steglitz-zehlendorf/politik-und-verwaltung/aemter/strassen-und-gruenflaechenamt/tiefbau/artikel.104719.php
   Radweganlagen in Bau/Planung
   Keine Aktualiasierung seit langer Zeit...
** <2018-09-21 Fr> <2018-08-07 Di> [#B] http://www.berlin.de/ba-tempelhof-schoeneberg/politik-und-verwaltung/aemter/strassen-und-gruenflaechenamt/strassen/artikel.380281.php
   Leider ist die Straßenbauliste zurzeit nicht verfügbar... (jetzt
   ist sie aber wieder da)
   Alte URL: http://www.berlin.de/ba-tempelhof-schoeneberg/organisationseinheit/tiefbau/index.html
** <2018-09-21 Fr> <2018-08-27 Mo> [#A] http://www.berlin.de/ba-treptow-koepenick/politik-und-verwaltung/aemter/strassen-und-gruenflaechenamt/tiefbau/artikel.118918.php
   Alte URL und Anweisungen: http://www.berlin.de/ba-treptow-koepenick/organisationseinheiten/tief/index.html
   Achtung: auch die Excel-Datei in der Gruppe "Neubau" prüfen
* Fahr-Rat
** <2018-08-23 Do> <2017-09-19 Di> https://www.berlin.de/ba-charlottenburg-wilmersdorf/verwaltung/aemter/ordnungsamt/strassenverkehr-parken/artikel.176925.php
   letztes Protokoll: 5. (? sollte es nicht 3. sein?) Sitzung der 5. Wahlperiode
   durchgesehen ab: 11. Sitzung

   Zurzeit wird 4x im Jahr getagt.
** <2018-05-07 Mo>              Friedrichshain-Kreuzberg fehlt
** <2018-08-23 Do> <2016-06-09 Do> https://www.berlin.de/ba-lichtenberg/aktuelles/buergerbeteiligung/artikel.510064.php
   Bis Radtour_09.06.2016 durchgesehen
** <2018-05-07 Mo>              Marzahn-Hellersdorf fehlt (wird ab Juli 2017 eingerichtet)
   Siehe: http://www.gruenemarzahnhellersdorf.de/2017/fahrrat-marzahn-hellersdorf-nimmt-die-arbeit-auf/
** <2018-05-07 Mo>              Mitte fehlt
** <2018-08-23 Do> <2018-03-17 Sa> https://fahrradfreundliches-neukoelln.de/tag/fahr-rat
   Nicht offiziell, keine Protokolle.
** <2018-08-23 Do> <2018-02-27 Di> https://www.berlin.de/ba-pankow/politik-und-verwaltung/gremien/beiraete/artikel.394180.php
   letztes Protokol: 21.06.16
   erstes Protokoll: 10.09.14
** <2018-05-07 Mo>              Reinickendorf fehlt
   Der Fahr-Rat-Link verweist auf
   https://www.berlin.de/ba-reinickendorf/politik-und-verwaltung/beauftragte/fahrradbeauftragter/
   --- ist aber eine weitgehend leere Seite.
** <2018-08-23 Do> <2015-09-29 Di> http://fahrrat-spandau.de/index.php?id=protokolle-der-sitzungen
   Website ist zurzeit ([2017-07-30 So]) kaputt: "Website im
   Wartungsmodus"

   letztes Protokoll: 7. Sitzung (8. - 10.: nicht genehmigt und nicht sichtbar)
   Protokolle durchgesehen ab 1. Sitzung

   Tagesordnungen existieren bis zur 11. Sitzung, aber kaum
   Informationsgehalt.

   https://www.berliner-woche.de/spandau/c-verkehr/fahrrat-tagt-wieder_a166859 (Sitzung am [2018-06-20 Mi])
** <2018-05-07 Mo>              Steglitz-Zehlendorf fehlt
** <2018-08-23 Do> <2018-03-15 Do> http://www.berlin.de/ba-tempelhof-schoeneberg/politik-und-verwaltung/gremien-und-ansprechpartner/fahrrat/artikel.387433.php
   durchgesehen ab 06.11.2014.
** <2018-08-23 Do> <2018-03-12 Mo> https://www.berlin.de/ba-treptow-koepenick/politik-und-verwaltung/aemter/stadtentwicklungsamt/stadtplanung/artikel.351102.php
   "AG Radverkehr"

   Durchgesehen bis: Präsentation Tief 10. AG_Radverkehr,
   "Protokoll 10. AG Rad" ist nicht mit allen PDF-Viewern (z.B. xpdf)
   lesbar.

   Nächster Termin voraussichtlich 2018-10-01
* alte URLs
** alte separate Bezirks-URLs
*** Berlin, Verwaltung
**** <2012-09-14 Fr> <2012-09-14 Fr> http://www.stadtentwicklung.berlin.de/aktuell/pressebox/archiv.shtml
     Pressearchiv der Sentasverwaltung für Stadtentwicklung
     Fast täglich Meldungen zu Berliner Verkehrsthemen.
*** Pressearchive der Berliner Bezirke
**** <2012-09-14 Fr> <2012-09-13 Do> http://www.berlin.de/ba-charlottenburg-wilmersdorf/presse/
     Charlottenburg-Wilmersdorf
**** <2012-09-14 Fr> <2012-09-13 Do> http://www.berlin.de/ba-friedrichshain-kreuzberg/aktuelles/pressemitteilungen/
     Friedrichshain-Kreuzberg

     Das neue Archiv hat Pressemitteilungen seit 2007. Zwischen
     2006-06-02 und 2006-11-06 wurden Pressemitteilungen des alten
     Archivs (nicht mehr verfügbar) überprüft.
**** <2012-09-14 Fr> <2012-09-14 Fr> http://www.berlin.de/ba-lichtenberg/presse/
     Lichtenberg
**** <2012-09-14 Fr> <2012-09-13 Do> http://www.berlin.de/ba-marzahn-hellersdorf/aktuelles/presse/
     Marzahn-Hellersdorf
**** <2012-09-14 Fr> <2012-09-14 Fr> http://www.berlin.de/ba-mitte/aktuell/presse/
     Mitte
**** <2012-09-14 Fr> <2012-09-13 Do> http://www.berlin.de/ba-neukoelln/presse/
     Neukölln
**** <2012-09-14 Fr> <2012-09-14 Fr> http://www.berlin.de/ba-pankow/presse/
     Pankow
**** <2012-09-14 Fr> <2012-09-14 Fr> http://www.berlin.de/ba-reinickendorf/presse/
     Reinickendorf

     Loch zwischen 2007-03-22 und 2007-05-29.
**** <2012-09-14 Fr> <2012-09-13 Do> http://www.berlin.de/ba-spandau/presse/
     Spandau
**** <2012-09-14 Fr> <2012-09-14 Fr> http://www.berlin.de/ba-steglitz-zehlendorf/presse/
     Steglitz-Zehlendorf
**** <2012-09-14 Fr> <2012-09-14 Fr> http://www.berlin.de/ba-tempelhof-schoeneberg/presse/
     Tempelhof-Schöneberg
**** <2012-09-14 Fr> <2012-09-14 Fr> http://www.berlin.de/ba-treptow-koepenick/presse/
     Treptow-Köpenick
** <2010-11-03 Mi> <2010-08-20 Fr> http://www.cdu-fraktion-tk.de/4_87_I-N-F-O-R-M-A-T-I-O-N-E-N--und--I-N-T-E-R-A-K-T-I-V_Amtsblaetter-2010.html
   Bessere Qualität als die Version von kulturbuch-verlag.de,
   Inhaltsverzeichnis verlinkt, aber wird leider nicht mehr
   aktualisiert...

   Amtsblätter Berlin (Bezirksämter)

   bereits überprüft:
   * in 2010:
     * 1..14, 17..26, 28..34
   * in 2009:
     * 12, 24, 25, 26, 29, 30, 31, 32, 33, 34, 35, 36, 37, 40, 41, 42,
       43, 44, 45, 46, 47, 48, (49*), 50, 51, 52, 53
     * frühere nicht vorhanden
     * 27, 28, 49 sind uninteressant
     * 38, 39 fehlen

   Gleicher Link: http://www.cdu-fraktion-tk.de/index.php?ka=4&ska=87
* org stuff
#+STARTUP: customtime
# Local Variables:
# org-time-stamp-custom-formats: ("<%Y-%m-%d>" . "<%Y-%m-%d %H:%M>")
# End:
