=head1 Watch Sites for BBBike

URLs, die immer wieder neue Informationen enthalten können.

=head2 Berlin

=over

=item *

Pressearchiv der Sentasverwaltung für Stadtentwicklung:
L<http://www.stadtentwicklung.berlin.de/aktuell/pressebox/archiv.shtml>

Fast täglich Meldungen zu Berliner Verkehrsthemen. Letzte überprüfte Nachricht:
2006-11-10.

=back

=head2 Pressearchive der Berliner Bezirke

=over

=item *

Charlottenburg-Wilmersdorf:
L<http://www.berlin.de/ba-charlottenburg-wilmersdorf/presse/index.html>

Letzte überprüfte Nachricht: 2006-11-10.

=item *

Friedrichshain-Kreuzberg:
L<http://www.kreuzberg.de/index_23_de.html> (nur aktuelle
Mitteilungen, der Link zum Archiv ist kaputt)

Erste bearbeitetete Nachricht vom 2.6.2006 (evtl. wird es nach
Reparatur des Archivs weitere, frühere Nachrichten geben).

Letzte überprüfte Nachricht: 2006-11-06.

=item *

Lichtenberg:
L<http://www.berlin.de/ba-lichtenberg/presse/index.html>

Letzte überprüfte Nachricht: 2006-11-09.

=item *

Marzahn-Hellersdorf:
L<http://www.berlin.de/ba-marzahn-hellersdorf/aktuelles/presse/index.html>

Letzte überprüfte Nachricht: 2006-11-10.

=item

Mitte:
L<http://www.berlin.de/ba-mitte/index_23_hr.html>

Letzte überprüfte Nachricht: 2006-11-10.

=item *

Neukölln:
L<http://www.berlin.de/ba-neukoelln/presse/index.html>

Letzte überprüfte Nachricht: 2006-11-10.

=item *

Pankow:
L<http://www.berlin.de/ba-pankow/presse/index.html>

Letzte überprüfte Nachricht: 2006-11-09.

=item *

Reinickendorf:
L<http://www.reinickendorf.de/index_6121_de.html> (kein Archiv)

Beginn der Pressemeldungen nicht feststellbar.

Letzte überprüfte Nachricht: 2006-11-11.

=item

Spandau:
L<http://www.berlin.de/ba-spandau/presse/index.html>

Letzte überprüfte Nachricht: 2006-11-10.

=item *

Steglitz-Zehlendorf:
L<http://www.berlin.de/ba-steglitz-zehlendorf/presse/index.html>

Letzte überprüfte Nachricht: 2006-11-10.

=item *

Tempelhof-Schöneberg:
L<http://www.berlin.de/ba-tempelhof-schoeneberg/presse/index.html>

Letzte überprüfte Nachricht: 2006-11-10.

=item *

Treptow-Köpenick:
L<http://www.berlin.de/ba-treptow-koepenick/presse/index.html>

Letzte überprüfte Nachricht: 2006-11-10.

=back

=head2 Sonstige Themen.

=over

=item * Köpenicker Themen bei berlinforen.de:
L<http://berlinforen.de/viewforum.php?f=2>

Letzte überprüfte Nachricht: 2006-11-07.

=item * Nationaler Radverkehrsplan, Neuigkeiten in Berlin:
L<http://www.nationaler-radverkehrsplan.de/neuigkeiten/?kid=25>

Letzte überprüfte Nachricht: 2006-10-31.

=item * Nationaler Radverkehrsplan, Neuigkeiten in Brandenburg:
L<http://www.nationaler-radverkehrsplan.de/neuigkeiten/?kid=36>

Letzte überprüfte Nachricht: 2006-10-31.

=back

