=head1 Watch Sites for BBBike

URLs, die immer wieder neue Informationen enthalten können.

=head2 Berlin

=over

=item *

Pressearchiv der Sentasverwaltung für Stadtentwicklung:
L<http://www.stadtentwicklung.berlin.de/aktuell/pressebox/archiv.shtml>

Fast täglich Meldungen zu Berliner Verkehrsthemen. Letzter Check:
2006-08-22.

=back

=head2 Pressearchive der Berliner Bezirke

=over

=item *

Charlottenburg-Wilmersdorf:
L<http://www.berlin.de/ba-charlottenburg-wilmersdorf/presse/index.html>

Letzter Check: 2006-07-06.

=item *

Lichtenberg:
L<http://www.berlin.de/ba-lichtenberg/presse/index.html>

Letzter Check: 2006-07-06.

=item *

Neukölln:
L<http://www.berlin.de/ba-neukoelln/presse/index.html>

Letzter Check: 2006-08-18.

=item *

Steglitz-Zehlendorf:
L<http://www.berlin.de/ba-steglitz-zehlendorf/presse/index.html>

Letzter Check: 2006-08-21.

=item *

Tempelhof-Schöneberg:
L<http://www.berlin.de/ba-tempelhof-schoeneberg/presse/index.html>

Letzter Check: 2006-08-20.

=back

