# -*- perl -*-
# DO NOT EDIT, generated by ../inline2dist.pl from Strassen::Inline2

package Strassen::Inline2Dist;

package Strassen::Inline2;
require DynaLoader;
unshift @ISA, 'DynaLoader';
#use base 'DynaLoader';
$VERSION = "2.19";

bootstrap Strassen::Inline2 $VERSION;

1;
