# -*- perl -*-
# DO NOT EDIT, generated by ../inline2dist.pl from Strassen::Inline

package Strassen::InlineDist;

package Strassen::Inline;
require DynaLoader;
unshift @ISA, 'DynaLoader';
#use base 'DynaLoader';
$VERSION = "2.20";

bootstrap Strassen::Inline $VERSION;

1;
