#!/usr/local/bin/perl -w
# -*- perl -*-

#
# $Id: b2gmake,v 1.1 2003/08/12 22:38:46 eserte Exp $
# Author: Slaven Rezic
#
# Copyright (C) 1999,2003 Slaven Rezic. All rights reserved.
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl itself.
#
# Mail: eserte@cs.tu-berlin.de
# WWW:  http://user.cs.tu-berlin.de/~eserte/
#

while(<STDIN>) {
    s/^\.if\s+defined\(([^\)]+)\)/ifdef $1/;
    s/^\.if(.+)eq(.+)/ifeq $1 $2/;
    s/^\.if(.+)ne(.+)/ifneq $1 $2/;
    s/^\.else(\s+)/else$1/;
    s/^\.endif(\s+)/endif$1/;
    s/\$\{\.?MAKEFLAGS\}/-\${MAKEFLAGS}/g;
    s/\$\(\.?MAKEFLAGS\)/-\${MAKEFLAGS}/g;
    print;
}

__END__
