#!/usr/bin/perl -w

use strict;

use FindBin;
use lib ("$FindBin::RealBin/..",
	 "$FindBin::RealBin/../lib",
	);
use Strassen::Core;
use Strassen::GPX;

my $file = shift || die;
my $s = Strassen->new($file);
print $s->Strassen::GPX::bbd2gpx();
