#!/usr/bin/perl -w

use strict;

use FindBin;
use lib ("$FindBin::RealBin/..",
	 "$FindBin::RealBin/../lib",
	);
use Getopt::Long;
use Strassen::Core;
use Strassen::GPX;

sub usage {
    die <<EOF;
usage: $0 [-as route] [-xmlmod module] bbdfile
EOF
}

my $as = "track";
GetOptions("as=s" => \$as,
	   "xmlmod=s" => \$Strassen::GPX::use_xml_module,
	  ) or usage();

if ($Strassen::GPX::use_xml_module) {
    if ($Strassen::GPX::use_xml_module !~ m{^(XML::Twig|XML::LibXML)$}) {
	die "Only XML::Twig or XML::LibXML allowed for -xmlmod option";
    }
}

my $file = shift || usage();
my $s = Strassen->new($file);
my $s_gpx = Strassen::GPX->new($s);
print $s_gpx->bbd2gpx(-as => $as);
