#!/usr/bin/perl -w

use strict;

use FindBin;
use lib ("$FindBin::RealBin/..",
	 "$FindBin::RealBin/../lib",
	);
use Getopt::Long;
use Strassen::Core;
use Strassen::GeoJSON;

sub usage {
    die <<EOF;
usage: $0 [-compact] [-bbbgeojsonp] bbdfile
EOF
}

my $compact;
my $bbbgeojsonp;
GetOptions(
	   "compact!"     => \$compact,
	   "bbbgeojsonp!" => \$bbbgeojsonp,
	  ) or usage();

my $file = shift || usage();
my $s = Strassen->new($file);
my $s_geojson = Strassen::GeoJSON->new($s);
print $s_geojson->bbd2geojson(bbbgeojsonp => $bbbgeojsonp, pretty => !$compact, utf8 => $compact);
