#!/usr/bin/perl -w
# -*- perl -*-

#
# $Id: check_images,v 1.2 2002/11/23 17:31:40 eserte Exp $
# Author: Slaven Rezic
#
# Copyright (C) 2002 Slaven Rezic. All rights reserved.
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl itself.
#
# Mail: slaven.rezic@berlin.de
# WWW:  http://bbbike.sourceforge.net
#

# Überprüft, ob alle Bilder tatsächlich existieren

use strict;
use FindBin;
use lib ("$FindBin::RealBin/..", "$FindBin::RealBin/../lib");
use Strassen::Core;
use Object::Iterate qw(iterate);
use File::Basename;
#use Getopt::Long;

@Strassen::datadirs = ("$FindBin::RealBin/../data");

my @imagedir = ("$FindBin::RealBin/../images");
#  if (!GetOptions(
#  	       )) {
#      die "usage";
#  }

my $file = shift;

if (!$file) {
    die "File is missing";
}

my $s = Strassen->new($file) or die $!;

$file = $s->file; # absolute name
my $imgdir = dirname($file);
push @imagedir, $imgdir if -d $imgdir;

my $fail = 0;

iterate {
    my $cat = $_->[Strassen::CAT];
    if ($cat =~ /IMG:([^|]+)/) {
	my $f = $1;
    TRY: {
	    foreach my $dir (@imagedir) {
		last TRY if (-e "$dir/$f");
	    }
	    warn "Can't find IMG $f\n";
	    $fail++;
	}
    }
} $s;

exit($fail);
