#!/usr/bin/perl -w
# -*- perl -*-

#
# $Id: gpsman2gpx,v 1.1 2005/10/05 21:25:07 eserte Exp eserte $
# Author: Slaven Rezic
#
# Copyright (C) 2005,2009 Slaven Rezic. All rights reserved.
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl itself.
#
# Mail: slaven@rezic.de
# WWW:  http://www.rezic.de/eserte/
#

use strict;
use FindBin;
use lib ("$FindBin::RealBin/..",
	 "$FindBin::RealBin/../lib",
	);
use GPS::GpsmanData::Any;

sub usage () { die "usage: $0 file" }

my $file = shift || usage;
usage if (@ARGV);

my $self = GPS::GpsmanData::Any->load($file);
print $self->as_gpx;


__END__
