all:	unsupported-make

*:	unsupported-make

unsupported-make:
	@echo "*** Sorry, your make program is not supported."
	@echo "*** Please try fmake or freebsd-make or pmake from the BSD project."
	@echo "*** You can get it from http://www.sourceforge.net/projects/srezic"
	@echo "*** Debian users may install the freebsd-buildutils package."
	@echo ""
	@false
