### XXX Manually created
RSYNC=	rsync
BBBIKE_HOSTEUROPE_USER=	root
BBBIKE_HOSTEUROPE_SSH_HOST=	177.227.205.92.host.secureserver.net
BBBIKE_HOSTEUROPE_HOST=	bbbike.177.227.205.92.host.secureserver.net
BBBIKE_HOSTEUROPE_APACHE_DIR=	/srv/www/bbbike-webserver/
BBBIKE_MAPSERVER_URL=	http://bbbike.177.227.205.92.host.secureserver.net/cgi-bin/mapserv
BBBIKE_MAPSERVER_DIRECT=	http://bbbike.177.227.205.92.host.secureserver.net/mapserver/brb/
BBBIKE_SF_WWW=	http://sourceforge.177.227.205.92.host.secureserver.net
EMAIL=	slaven@rezic.de
MAPSERVER_PROG_RELURL=	/cgi-bin/mapserv
MAPSERVER_PROG_URL=	http://bbbike.177.227.205.92.host.secureserver.net/cgi-bin/mapserv
ALL_LAYERS=	gewaesser flaechen grenzen bahn qualitaet radwege orte handicap ampeln obst faehren fragezeichen blocked sehenswuerdigkeit route comments_route
