### XXX Manually created
RSYNC=	rsync
BBBIKE_RADZEIT_USER=	root
BBBIKE_RADZEIT_HOST=	78.47.225.30
BBBIKE_RADZEIT_APACHE_DIR=	/var/www/domains/radzeit.de/www/
BBBIKE_HOSTEUROPE_USER=	root
BBBIKE_HOSTEUROPE_HOST=	bbbike-pps-jessie
BBBIKE_HOSTEUROPE_APACHE_DIR=	/srv/www/bbbike-webserver/
BBBIKE_MAPSERVER_URL=	http://bbbike-pps-jessie/cgi-bin/mapserv
BBBIKE_MAPSERVER_DIRECT=	http://bbbike-pps-jessie/mapserver/brb/
BBBIKE_SF_WWW=	http://bbbike.sourceforge.net
EMAIL=	slaven@rezic.de
MAPSERVER_PROG_RELURL=	/cgi-bin/mapserv
MAPSERVER_PROG_URL=	http://bbbike-pps-jessie/cgi-bin/mapserv
ALL_LAYERS=	gewaesser flaechen grenzen bahn qualitaet radwege orte handicap ampeln obst faehren fragezeichen blocked sehenswuerdigkeit route comments_route
