### XXX Manually created
RSYNC=	rsync
BBBIKE_HOSTEUROPE_USER=	root
#BBBIKE_HOSTEUROPE_HOST=	lvps83-169-5-248.dedicated.hosteurope.de
BBBIKE_HOSTEUROPE_HOST=	bbbike.de
BBBIKE_HOSTEUROPE_APACHE_DIR=	/srv/www/bbbike-webserver/
#BBBIKE_MAPSERVER_URL=	http://lvps83-169-5-248.dedicated.hosteurope.de/cgi-bin/mapserv
BBBIKE_MAPSERVER_URL=	http://bbbike.de/cgi-bin/mapserv
#BBBIKE_MAPSERVER_DIRECT=	http://lvps83-169-5-248.dedicated.hosteurope.de/mapserver/brb/
BBBIKE_MAPSERVER_DIRECT=	http://bbbike.de/mapserver/brb/
BBBIKE_SF_WWW=	http://bbbike.sourceforge.net
EMAIL=	slaven@rezic.de
MAPSERVER_PROG_RELURL=	/cgi-bin/mapserv
#MAPSERVER_PROG_URL=	http://lvps83-169-5-248.dedicated.hosteurope.de/cgi-bin/mapserv
MAPSERVER_PROG_URL=	http://bbbike.de/cgi-bin/mapserv
ALL_LAYERS=	gewaesser flaechen grenzen bahn qualitaet radwege orte handicap ampeln obst faehren fragezeichen blocked sehenswuerdigkeit route comments_route
