# -*- perl -*-
# DO NOT EDIT, generated by ../inline2dist.pl from VectorUtil::Inline

package VectorUtil::InlineDist;

package VectorUtil::Inline;
require DynaLoader;
unshift @ISA, 'DynaLoader';
#use base 'DynaLoader';
$VERSION = "1.09";

bootstrap VectorUtil::Inline $VERSION;

1;
